### ISSUE TITLE
[BUG] DNS resolution only works on the node hosting coredns in a three-nodes K3S cluster with flannel CNI

### ISSUE THREAD

**Issue by qclemence** [Azure/AKS-Edge#101]
**Describe the bug**
On a three-nodes K3S AKS EE cluster, DNS resolution seems only work on the master node (the node hosting the coredns pod).

**To Reproduce**
1. Deploy a K3S cluster with 3 nodes and use Flannel as CNI
2. Deploy a ReplicatSet and a Service
3. Deploy a debug-1 pod (Busybox) on master node and execute 'nslookup <service name>.default.svc.cluster.local' (it works)
4. Deploy a debug-2 pod (Busybox) on a worker node and execute 'nslookup <service name>.default.svc.cluster.local' (failed)

**Expected behavior**
The nslookup command should work on a pod running either the master or worker node.

**Screenshots**

**Environment (please complete the following information):**
- AKS Edge Essentials Version: 1.1.80.0
- Kubernetes version: 1.24.6
- Nested virtualization environment:
	- L0 Host OS: Windows Server 2022 Standard Evaluation running bare-metal (2 x CPU 10 cores Intel E5-2650v3, 224 Go RAM)
	- L1 3 VMs : Windows Server 2022 Standard Evaluation (5 vCPUs, 24 Go RAM)
	- L2 1 Linux nested VM running on each L1 VM (4 vCPUs, 16 Go RAM)
	- Internal virtual switch on the L0 host
- Flannel as CNI

**Additional context**
- in attachment, the aks ee config files for the 3 nodes and the Kubernetes objects deployed for debugging [aks_ee_config_files.zip](https://github.com/Azure/AKS-Edge/files/11150643/aks_ee_config_files.zip).
- ping works between all the virtual machines (L1 and L2) through the virtual switch network
- ping DOES NOT work between the L2 virtual machines via the flannel interfaces

```
❯ kubectl get nodes -A -o wide
NAME                STATUS   ROLES                       AGE     VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE            KERNEL-VERSION    CONTAINER-RUNTIME
aks-ee-vm-1-ledge   Ready    control-plane,etcd,master   6h39m   v1.24.6+k3s-   172.30.1.4    <none>        CBL-Mariner/Linux   5.15.94.1-1.cm2   containerd://1.6.8-k3s1
aks-ee-vm-2-ledge   Ready    control-plane,etcd,master   3h38m   v1.24.6+k3s-   172.30.1.6    <none>        CBL-Mariner/Linux   5.15.94.1-1.cm2   containerd://1.6.8-k3s1
aks-ee-vm-3-ledge   Ready    control-plane,etcd,master   3h32m   v1.24.6+k3s-   172.30.1.9    <none>        CBL-Mariner/Linux   5.15.94.1-1.cm2   containerd://1.6.8-k3s1


❯ kubectl get pods -A -o wide
NAMESPACE     NAME                                              READY   STATUS      RESTARTS       AGE     IP           NODE                NOMINATED NODE   READINESS GATES
default       debug-node1                                       1/1     Running     1 (82m ago)    89m     10.42.0.14   aks-ee-vm-1-ledge   <none>           <none>
default       debug-node2                                       1/1     Running     1 (79m ago)    89m     10.42.2.4    aks-ee-vm-2-ledge   <none>           <none>
default       nginx-rs-ffl6p                                    1/1     Running     1 (151m ago)   3h28m   10.42.0.10   aks-ee-vm-1-ledge   <none>           <none>
default       nginx-rs-hgtzx                                    1/1     Running     0              3h28m   10.42.3.2    aks-ee-vm-3-ledge   <none>           <none>
default       nginx-rs-zt2hm                                    1/1     Running     0              3h28m   10.42.2.2    aks-ee-vm-2-ledge   <none>           <none>
kube-system   coredns-574fccb484-t9zqx                          1/1     Running     1 (151m ago)   6h39m   10.42.0.11   aks-ee-vm-1-ledge   <none>           <none>
kube-system   kube-vip-cloud-provider-0                         1/1     Running     1 (151m ago)   6h39m   10.42.0.9    aks-ee-vm-1-ledge   <none>           <none>
kube-system   kube-vip-ds-8q97c                                 1/1     Running     1 (151m ago)   6h39m   172.30.1.4   aks-ee-vm-1-ledge   <none>           <none>
kube-system   kube-vip-ds-nqz2n                                 1/1     Running     0              3h38m   172.30.1.6   aks-ee-vm-2-ledge   <none>           <none>
kube-system   kube-vip-ds-v6lr2                                 1/1     Running     0              3h32m   172.30.1.9   aks-ee-vm-3-ledge   <none>           <none>
kube-system   local-path-provisioner-5c64749b78-zct5s           1/1     Running     1 (151m ago)   6h39m   10.42.0.12   aks-ee-vm-1-ledge   <none>           <none>


❯ kubectl get svc -A -o wide
NAMESPACE     NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE     SELECTOR
default       kubernetes    ClusterIP   10.43.0.1       <none>        443/TCP                  6h40m   <none>
default       web-service   ClusterIP   10.43.190.163   <none>        8080/TCP                 102m    app.kubernetes.io/name=nginx-rs
kube-system   kube-dns      ClusterIP   10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP   6h40m   k8s-app=kube-dns
```

**Comment by fcabrera23** [comment]
Hi @qclemence,

Thanks for the detailed information.  We will try to reproduce it and get back to you. In the meantime, the AKS Linux VM will drop the ICMP ping traffic by default, so you wont be able to ping between those L2 VMs. However, you can enable the ICMP traffic using the following command:
 `Invoke-AksEdgeNodeCommand -NodeType Linux -command "sudo iptables -A INPUT -p ICMP -j ACCEPT"`

Thanks,
Francisco

**Comment by qclemence** [comment]
Hi @fcabrera23 ,

I forgot to mention that I enabled ICMP traffic with the command you provided.
With this I can ping the L2 VMs through the "external" network (172.30.1.0/24) but not through the flannel interfaces (10.42.0.0/24, 10.42.2.0/24, 10.42.3.0/24)

Thanks,
Quentin

**Comment by fcabrera23** [comment]
Hi @qclemence,

Could you please try running the following commands in the 3 nodes? We've encountered a firewall issue that will be fixed in our next release. 

```
Invoke-AksEdgeNodeCommand -NodeType Linux "sudo iptables -A INPUT -p udp --dport 8472 -j ACCEPT
Invoke-AksEdgeNodeCommand -NodeType LInux "sudo iptables-save | sudo tee /etc/systemd/scripts/ip4save"
```

Thanks,
Francisco

**Comment by qclemence** [comment]
Hi @fcabrera23,

After running the commands you provide in the 3 nodes, the DNS resolution works fine from all pods.

Thanks for your prompt response,
Quentin
