### ISSUE TITLE
[Question] Shared storage between host os and linux node on single cluster deployment

### ISSUE THREAD

**Issue by dsfrederic** [Azure/AKS-Edge#107]
**Describe scenario**

I need to access the same data first on the linux node and then host windows OS.

Question
What would be the best method to do this?

**Comment by fcabrera23** [comment]
Hi @dsfrederic,

Thanks for reaching out. File/Folder sharing between the Windows host OS and the Linux node is a feature we already have in EFLOW, and we are planning to port it to AKS EE in the upcoming months.

Thanks,
Francisco

**Comment by JMayrbaeurl** [comment]
Any update on this?

**Comment by dsfrederic-cgk** [comment]
@fcabrera23 Any updates on this?

**Comment by fcabrera23** [comment]
Hi @dsfrederic, 

Please reach out to AKS Edge Essentials Inquiry <aksee-inquire@microsoft.com> for further questions.

Thanks,
Francisco
