### ISSUE TITLE
[Question] Any way to update the cluster's configuration post deployment?

### ISSUE THREAD

**Issue by JulesP96** [Azure/AKS-Edge#109]
Is there any way to update the `aksedge-config.json` to either update the cluster's IP Range configuration, memory, CPU count or others properties even if 'New-AksEdgeDeployment' cmdlet was already executed?

Maybe this is a planned feature?

**Comment by fcabrera23** [comment]
Hi @JulesP96,

Thanks for reaching out. Unfortunately, there's no way to change the VM configurations after the VM is deployed. However, this is a feature that we are planning to introduce in our future updates. 

Thanks,
Francisco

**Comment by JMayrbaeurl** [comment]
@fcabrera23 Could we at least get full documentation in the 'how-to' section on how to increase e.g. the memory of a node in single node deployment?

**Comment by fcabrera23** [comment]
Hi @JMayrbaeurl,

We are still considering providing a PS cmdlet to update configurations. In the meantime, all configurations must be set during deployment. Please check the [Deployment configuration JSON parameters](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-deployment-config-json) for all the available settings.  Also, adding @SummerSmith  who will continue to help with this repo. 

Thanks, 
Francisco

**Comment by rcheeran** [comment]
Today, the only way to change resource configurations on the VM is via redeployment. The ability to edit a VM's footprint after deployment is on the roadmap. Will update via release notes when we get to that.
