### ISSUE TITLE
 Documentation - settings in aide-userconfig  (VhdxPath)

### ISSUE THREAD

**Issue by kvietmeier** [Azure/AKS-Edge#116]
**Describe scenario**
Trying to optimize my installation on Windows 11 it would be helpful to better understand the meaning of settings and files.

**Question/s**
What is the difference between:  "aide-userconfig.json" and "aksedgeconfig.json" 
And when are they used?  They seem redundant but slightly different.

And why are they different across 2 Windows 11 hosts?

Specifically - 
I can't find it documented anywhere what the settings under "InstallOptions" in "aide-userconfig.json" do.  Are these HyperV settings?  Can I use a second drive letter here to store my Linux VM so I can allocate a large amount of storage and not burden my system drive with IO. 

```
{
    "SchemaVersion": "1.1",
    "Version": "1.0",
    "AksEdgeProduct": "AKS Edge Essentials - K3s",
    "AksEdgeProductUrl": "",
    "InstallOptions": {
        "InstallPath": "",
        "VhdxPath": ""
    },
    "VSwitch": {
        "Name": "",
        "AdapterName": ""
    },
```

**Comment by parameshbabu** [comment]
hi, please see https://github.com/Azure/AKS-Edge/blob/main/tools/modules/AksEdgeDeploy/README.md for the aide-userconfig.json. This is for automated install of the AKS EE msi, so exposes the parameters used for msi installation as well. The Actual cluster configuration is defined in the aksedge-config.json.

Can I use a second drive letter here to store my Linux VM>>
 Yes you can. Specify the VhdxPath to be on the second drive.  See https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine#install-aks-edge-essentials

**Comment by kvietmeier** [comment]
That helps, thanks!  I had missed that README.
