### ISSUE TITLE
Windows 11:  Dual Interface Confguration

### ISSUE THREAD

**Issue by kvietmeier** [Azure/AKS-Edge#122]
**Describe scenario**
I am using an Intel Ghost Canyon NUC with both WiFi and wired ethernet available running Windows 11.

I was using the NUC previously with Hyper-V for some Mariner and Ubuntu VMs using an external vswitch bridged to the WiFi interface while using the wired ethernet for the OS. It was working fine, the VMs could get out to the internet and connect to other systems on the local 192.168.1.1 network.

The first time I installed AKS-EE I used the existing vSwitch bridged to WiFi - as per the instructions. Everything appeared to be  working, I was even able to follow the GitOps demo and get that working. The problems started after a reboot of the NUC. After a reboot I had to reconnect the WiFi adapter to the network which seemed to work - I could run kubectl commands.  But the cluster/VM/network became very unstable after that and eventually stopped communicating.

I then started getting certificate errors when trying to run "Invoke-AKS-EdgeNodeCommand".  

During this time the existing Mariner VMs had no issues communicating via the same switch.

Thinking there was some existing configuration interfering I removed everything, including HyperV and started over. 

- I tried bridging the wired ethernet but that didn't work so I went back to a dual network setup.
- I went back to the bridged WiFi setup and everything installed fine and looked like it was working, until I shutdown/restarted the NUC and now I'm back to the original situation.
- Note that another NUC on the same network with just a WiFi connection, no w3ired Ethernet, is working fine, very stable, even aftre reboots etc.

**Question**
What is the best way to setup AKS-EE on a Windows 11 node?
Can you use a dual connection like I have or can you only use WiFi?  Bridging and sharing the wired connection didn't appear to work (maybe if the WiFi interface is completely removed?)
Can you use HyperV for other VMs while AKLS-EE is using it?

Thanks!

**Comment by fcabrera23** [comment]
Hi @kvietmeier,

Thanks for reaching out.  We are working on fixing an open issue with WiFi virtual switches for our next update.  Answering below your questions:

1) If you need just one node, use a singe machine cluster, and we will create the internal switch for you. If you're using Scalable Cluster, the best option is to use an Ethernet connection to create your External Virtual Switch. 
2) For Dual Nics, please check [Configure multiple Nics](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-multi-nic).  Bridging is something that we do not recommend.
3) Yes our VM lifecycle is managed completely by us and shouldn't impact your other VMs running on the host OS. However, we recommend not changing the AKS EE VM configurations using Hyper-V Manager. 

Thanks,
Francisco

**Comment by kvietmeier** [comment]
@Francisco,

This helps clarify things a bit and I may have used the term bridge incorrectly.

HyperV is creating a bridge when I allow HyperV and the host OS to share the same interface.

On one system I only have a WiFi connection and I followed the instructions to create an external vSwitch.  This system works perfectly as expected.

On another system (the one not working) my primary interface is a wired connection but it also has a WiFi interface.  Previous to AKS-EE I had created an external vSwitch bridged to the WiFi connection for the VMs and it was working fine - sort of - I would still need to manually  reconnect to the WiFi after a reboot. AKS-EE will install fine on this system and even work properly, until a restart, then you lose connection to the VM.

Interestingly - when I tried disabling the WiFi interface and just share the wired connection I couldn't get AKS-EE to install/work at all.

I'm inclined to think that using both interfaces is more effort than it is worth and may just go to WiFi only on both.  But I will give the dual interface setup a try before reverting to one interface.  


A note on single vs. multiple nodes and networking:
If you want to be able to access the apps running in the cluster from the local network you need the external vSwitch, it just makes everything much, much easier.  That isn't clear in the docs but it comes out in some blog posts and issues. So - if you want to be able to give your apps IP addresses on your local network you should create a multi-node cluster with a single node.

VM lifecycle - The VMs do not show up in HyperV Manager, only the vSwitch.

**Comment by kvietmeier** [comment]
Closing:   Collapsing onto the the WiFi interface seems to have worked (until updating the BIOS and rebooting but that is another issue)
