### ISSUE TITLE
[Question] Is Windows Server Essentials 2022 a valid option for OS ?

### ISSUE THREAD

**Issue by adyekjaer** [Azure/AKS-Edge#124]
Hey Guys,

It's not entirely clear from the documentation if Windows Server Essentials 2022 is a valid operating system for running AKS Edge Essentials. 

There are no specific mentions of the server versions [here](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-system-requirements)

Let me know - thank you!

**Comment by fcabrera23** [comment]
Hi @adyekjaer,

Thanks for reaching out. Windows Server Essentials 2022 has all the necessary components to run AKS Edge Essentials, so it should work.

Thanks,
Francisco
