### ISSUE TITLE
[BUG] Windows Node status "NotReady" after restarting Host machine

### ISSUE THREAD

**Issue by edgarhal** [Azure/AKS-Edge#127]
**Describe the bug**
The Windows Node status stays as "NotReady" after restarting the Host machine when deploying a "SingleMachineCluster".
Initially, the Windows Node works fine before restarting the Host machine, even after executing the below commands:

- Stop-AksEdgeNode -NodeType Windows
- Stop-AksEdgeNode -NodeType Linux
- Start-AksEdgeNode -NodeType Linux
- Start-AksEdgeNode -NodeType Windows

Once the Host machine gets rebooted, the Windows Node status stays as "NotReady".

**To Reproduce**
1. Deploy Single Machine Cluster
2. Verify the Windows Node status is "Ready"
3. Stop-AksEdgeNode -NodeType Windows
4. Stop-AksEdgeNode -NodeType Linux
5. Restart Host Machine
6. Start-AksEdgeNode -NodeType Linux
7. Start-AksEdgeNode -NodeType Windows
8. The Windows Node status is "NotReady"

**Expected behavior**
The Windows Node should be in "Ready" state even after the Host Machine reboots.

**Screenshots**
The below image shows how the Windows Node is registered but cannot reach the "Ready" state.

![image](https://github.com/Azure/AKS-Edge/assets/67426682/06d30adf-172b-41f0-af72-933cdb30d3bc)

![image](https://github.com/Azure/AKS-Edge/assets/67426682/98fd077e-fa83-479e-9d3a-fa7e3c582d8b)

**Environment:**
 - AKS Edge Essentials Version = 1.2.414.0
 - Kubernetes version = k8s 1.25.4
 - Windows Host OS:
    - Edition: Windows 11 Enterprise
    - Version: 22H2 Build 23486.1000
    - Virtual Machine: None

**Additional context**
None.

**Comment by patrickvargas** [comment]
I`ve found a way to get it working.
Instead leting AKSEdge create the aksedgesw-ext vSwitch on Hyper-V, do that yourself and rename the newly vSwitch created from vEthernet(aksedgesw-ext) to just aksedgesw-ext.
![image](https://github.com/Azure/AKS-Edge/assets/25593027/1fccfcb7-04e9-48b2-8b8f-3b5b0294e856)

![image](https://github.com/Azure/AKS-Edge/assets/25593027/8386c2f4-1387-47da-81e8-dbda6ffc96c4)

Another step that I`m doing is shutdown just the Windows node using Stop-AksEdgeNode -NodeType Windows before shutdown the computer or VM if nested VM, I`m not sure if this is an essential step, but it`s working fine after all this.
![image](https://github.com/Azure/AKS-Edge/assets/25593027/602b3778-8ec4-4540-b63c-6d3ef7b296ac)

**Comment by patrickvargas** [comment]
@fcabrera23, I have to do a normal installation again to check if the issue is still there. Give me sometime and I`ll back to you if the answer. Thanks.
