### ISSUE TITLE
AKS Edge Essentials and Azure IoT Edge Compatibility

### ISSUE THREAD

**Issue by payalgaikwad42** [Azure/AKS-Edge#133]
**scenario**
I have an opc ua publisher module deployed on azure iotedge which is used to connect with my kepserver to read the tags. I am using opc publisher direct methods to make changes in pn.json file and My data is being sent to the IoT hub.

**Question**
1. If I decide to move opc publisher to AKS and deploy it just as a container. Is there any way I will be able to do cloud to device communication? 
2. Is there any way to send data to IoT Hub from AKS edge essentials deployed modules?
3. Are any of IoT Hub, IoT Edge features like C2D messaging, Direct methods incorporated in Edge Essentials for remote control?

I am just wondering about this, The documents I have gone through does not specify anything like this, that's why the questions for my better understanding.

Thank you in Advance!!

**Comment by payalgaikwad42** [comment]
@fcabrera23 
I am not sure If you are related to this or not. But I saw you have answered few of the questions related to AKS. It would great  if you can help me with this or redirect the question to someone who knows it. 

Thank you so much!

**Comment by fcabrera23** [comment]
Hi @payalgaikwad42,

Thanks for reaching out - Could you please share a way to contact you? I'l make the appropriate team contacts you to solve this issue.

Thanks,
Francisco

**Comment by payalgaikwad42** [comment]
Hi @fcalandra, You can contact me on my mail payalgaikwad42@gmail.com. I just had a query about whether AKS edge essentials will replace azure IoT Edge or not?

Thank you for your support.

**Comment by fcabrera23** [comment]
Hi @payalgaikwad42,

I just sent you an email - Then the short question is No, IoT Edge and AKS-EE will coexist as they do right now. They are different products with different technologies, although they could be used for similar scenarios. I'll be sure to share with you a more in-detail explanation via email.

Thanks,
Francisco

**Comment by payalgaikwad42** [comment]
Hi Francisco,

Thank you so much. I look forward to new information.
To give you more context, We are working on a project where we are using
the OPC Publisher IoT Edge module to read data from kepserver and send it
to IoT Hub, we are using OPC Publisher direct methods to make changes to
the pn.json file.
We were thinking about moving OPC Publisher to AKS Edge Essentials. So I
was looking into how to consume those direct methods.
 Also as of now IoT Hub is the central messaging hub, If I connect AKS to
Azure ARC, it provides monitoring and no messages routing features right?

Thank you,
Payal Gaikwad

**Comment by payalgaikwad42** [comment]
Hi @fcabrera23 
I have not heard from your team in a while. 
I also have a doubt in command line arguments in OPC publisher IoT Edge module 2.9 version. I have following parameters set for OPC Publisher Container create option.

<img width="445" alt="image" src="https://github.com/Azure/AKS-Edge/assets/42204123/c5642456-e189-490e-b975-921c70b79747">

As you can see I want messages to be sent to IoT Hub when message count is 10. But I am observing a behavior where I receive more than 10 messages in one IoT Hub message or less than 10 entries as shown below:
<img width="386" alt="image" src="https://github.com/Azure/AKS-Edge/assets/42204123/8d9b7852-6bbc-421a-ad08-0f4544f8a82c">

<img width="452" alt="image" src="https://github.com/Azure/AKS-Edge/assets/42204123/acd40768-e046-4e7c-8a33-7da28375b1dc">

1. What should be the values of si, ms and bs parameters in this case? I have gone through documentation but different documentation has different explanation. 
2.  Also source timestamp in OPC publisher data is the time at which data was received from kepware or time at which data was changed on the kepware?

**Comment by payalgaikwad42** [comment]
following is the recent entry with only 3 data points in a batch:
<img width="484" alt="image" src="https://github.com/Azure/AKS-Edge/assets/42204123/9bc469cc-b7d3-4b64-a6c3-1881b53f3382">

I am quite confused , what is the use of batch size parameter if it does not send messages accordingly to the Iot Hub

**Comment by fcabrera23** [comment]
Hi @payalgaikwad42,

Thanks for reaching out.  Please double check your inbox; i just send you another email.

Thanks,
Francisco

**Comment by razvan-r** [comment]
> Hi @payalgaikwad42,
> 
> I just sent you an email - Then the short question is No, IoT Edge and AKS-EE will coexist as they do right now. They are different products with different technologies, although they could be used for similar scenarios. I'll be sure to share with you a more in-detail explanation via email.
> 
> Thanks, Francisco

Hello @fcabrera23,

We are also in the process of choosing between AKS Edge and Azure IoT Edge; we also don't know which one will outlast the other.
Can you please share your explanation at this email address: razvanradu2005@gmail.com  

Thanks,
Razvan
