### ISSUE TITLE
[Question] Clarification on AKS Edge Essentials Monthly Releases and Kubernetes Version Compatibility

### ISSUE THREAD

**Issue by erwinkersten** [Azure/AKS-Edge#135]
I'm currently seeking some clarification regarding the monthly releases of AKS Edge Essentials and their compatibility with specific Kubernetes versions. I have a couple of questions regarding this matter:

1.  **Kubernetes Version Alignment**: How is the chosen Kubernetes version in AKS Edge Essentials aligned with the Kubernetes versions supported within AKS Cloud? For instance, I noticed that both the AKS EE releases for June and August are utilizing Kubernetes version 1.25.x, whereas AKS Cloud introduced version 1.27 as generally available starting from July 2023 (reference: [AKS Kubernetes Release Calendar](https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar)).

1. **Version Customization:** Can we anticipate that the AKS EE installation will consistently deploy only one designated version of native Kubernetes and the K3s distribution? Alternatively, will there be an option in the future to specify a particular Kubernetes version during the initial installation process?

Any insights on these questions would be greatly appreciated. Thank you for your time and assistance!

Best regards,
Erwin Kersten

**Comment by fcabrera23** [comment]
Hi @erwinkersten,

Adding @chrisdats  to help you clarify your questions.

Thanks,
Francisco

**Comment by erwinkersten** [comment]
@chrisdats and @fcabrera23  In the September release notes, it was announced that AKS EE now supports two Kubernetes versions: K8s 1.26.3, 1.25.7 for standard Kubernetes, and for the K3s distribution, it supports 1.26.6+k3s, 1.25.8+k3s. This should address the second part of my inquiry.

However, I seem to be facing an issue with the current Deployment scheme (v1.9) as it doesn't seem to offer an option to specify a version. I might be overlooking something, but I'm unsure about how this is supposed to function. Could you provide some insights or guidance on this matter?

**Comment by rcheeran** [comment]
Thanks for sharing those links. Yes the previous releases can be found at download.microsoft.com.
We also have short links here: 
https://aka.ms/aks-edge/k3s-msi-1.25
https://aka.ms/aks-edge/k8s-msi-1.25

**Comment by rcheeran** [comment]
Created a bug internally to update our scripts to enable users to choose the version.

**Comment by scooley** [comment]
Changing from question to enhancement so we track this better.

**Comment by parameshbabu** [comment]
[Download AKS EE](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine#download-aks-edge-essentials) has been updated with the supported version links.
