### ISSUE TITLE
[Feedback] Update procedure AKS Edge Essentials

### ISSUE THREAD

**Issue by erwinkersten** [Azure/AKS-Edge#137]
The Start-AksEdgeUpdate cmdlet produces the output message "Update complete. Please restart your PowerShell instance and execute Start-AksEdgeControlPlaneUpdate and Start-AksEdgeWorkerNodeUpdate," regardless of whether it's applied to a single machine or a scale-out deployment.

If my understanding is correct in a single machine deployment, initiating the update process is as straightforward as executing ```Start-AksEdgeUpdate``` and running ```Start-AksEdgeControlPlaneUpdate -firstControlPlane $True```. However, it's worth noting that this command generates the message mentioned above, which may be confusing if you run a single  machine.

For clarity, I think that also the documentation can be enhanced [AKS Edge Essentials update - AKS hybrid | Microsoft Learn](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-update). Presently, the documentation lists sequential steps for the update process. A more clear or effective approach would involve segmenting the instructions for single-machine and scale-out deployments (in combination with the output of the Start-AksEdgeUpdate command).

Erwin

**Comment by fcabrera23** [comment]
Hi @erwinkersten,

Thanks for reaching out. We will improve the documentation for further clarity. The `Start-AksEdgeUpdate` and `Start-AksEdgeControlPlaneUpdate` are separate steps. The same steps are used for single and scalable clusters, so if you only run one command nodes won't get updated. 

**Single machine clusters** 
1. Run `Start-AksEdgeUpdate` 
1. Run `Start-AksEdgeControlPlaneUpdate`
1. Run if you have Windows node-enabled `Start-AksEdgeWorkerNodeUpdate`

**Multi machine clusters** 
1. Run `Start-AksEdgeUpdate` 
1. Run `Start-AksEdgeControlPlaneUpdate -firstControlPlane true`
1. On the other control plane nodes, run `Start-AksEdgeControlPlaneUpdate` 
1. On the other worker nodes run `Start-AksEdgeWorkerNodeUpdate`

Thanks,
Francisco
