### ISSUE TITLE
[Feature] Expose log rotation configuration

### ISSUE THREAD

**Issue by EliiseS** [Azure/AKS-Edge#146]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to rotate the logs generated by K8s to avoid filing up my log volume. This issue is mitigated by setting the `Machines[].LinuxNode.LogSizeInGB` to a higher value, however still depending on the amount of logs produced by the cluster, this limit can also be reached. And given a VM with a limited disk size, this setting may not be as effective. 

**Describe the solution you'd like**

Expose the log rotation configuration as an option within the AKS EE config, as seen here: [Logging Architecture | Kubernetes](https://kubernetes.io/docs/concepts/cluster-administration/logging/#log-rotation)

**Describe alternatives you've considered**

- Potentially work around this problem by implementing your own daemonSet to clean up the logs for you, but that seems more of workaround than a real fix.
- Potentially modify kubelet after AKS EE has finished creation

**Comment by fcabrera23** [comment]
Hi @EliiseS,

If you want to change the logging settings, you can do it by changing the [Kubelet configuration](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/) settings. You can use the Copy-AksEdgeNodeFile and Invoke-AksEdgeNode commands to change the settings and apply the new ones.

Thanks,
Francisco
