### ISSUE TITLE
[BUG] Hyper-V Internal Switch is lost after a restart on Win11 Pro 22H2 22623.746

### ISSUE THREAD

**Issue by mitkox** [Azure/AKS-Edge#15]
**Describe the bug**
Hyper-V Internal Switch is lost after a restart on Win11 Pro 22H2 22623.746

1. **To Reproduce**
It is reproducible every time 
PS C:\aks\tools> Start-AksEdgeNode
C:\Program Files\AksEdge\nodectl.exe  compute vm start --name sof-divasile-sb-ledge failed to execute [Error: rpc error: code = Unknown desc = Endpoint Name sof-divasile-sb-ledgeInterface not found]
At C:\Program Files\WindowsPowerShell\Modules\AksEdge\0.7.22335.1024\AzureEFLOW.psm1:5254 char:9
+         throw "$command $arguments failed to execute [$err]"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (C:\Program File...face not found]:String) [], RuntimeException
    + FullyQualifiedErrorId : C:\Program Files\AksEdge\nodectl.exe  compute vm start --name sof-divasile-sb-ledge failed to execute [Error: rpc error: code = Unknown desc = Endpoint Name sof-divasile-sb-ledgeInterface not found]

2. **Expected behavior**
Start the AKS EE Node if there was the internal hyper-v switch present 

**Screenshots**

**Environment (please complete the following information):**
 - AKS Edge Essentials Version 0.7.22335.1024
 - Kubernetes version K3s 1.23.6 
 - Windows Host OS (please complete the following information):
    - Edition: Professional
    - Version: 22623
    - Virtual Machine: No

**Additional context**
The deployment of AKS EE is successful but after a restart, the internal Hyper-V switch disappears. 
aksedge-config.json
{
    "SchemaVersion": "1.1",
    "Version": "1.0",
    "DeployOptions": {
        "ControlPlane": false,
        "Headless": false,
        "JoinCluster": false,
        "NetworkPlugin": "flannel",
        "SingleMachineCluster": true,
        "TimeoutSeconds": 900,
        "NodeType": "Linux",
        "ServerTLSBootstrap": true
    },
    "EndUser": {
        "AcceptEula": true,
        "AcceptOptionalTelemetry": true
    },
    "LinuxVm": {
        "CpuCount": 4,
        "MemoryInMB": 4196,
        "DataSizeinGB": 30,
        "Ip4Address": "192.168.1.171"
    },
    "Network": {
        "VSwitch": {
            "Name": "",
            "Type": "",
            "AdapterName": ""
        },
        "ControlPlaneEndpointIp": "192.168.1.191",
        "Ip4GatewayAddress": "192.168.1.1",
        "Ip4PrefixLength": 24,
        "ServiceIPRangeSize": 0,
        "ServiceIPRangeStart": "192.168.1.151",
        "ServiceIPRangeEnd": "192.168.1.170",
        "DnsServers": [
            "192.168.1.1"
        ],
        "InternetDisabled": false,
        "Proxy": {
            "Http": "",
            "Https": "",
            "No": ""
        }
    }
}

**Comment by pilebas** [comment]
Exactly same issue observed on Win11 Enterprise (10.0.22621 Build 22621)

**Comment by fcabrera23** [comment]
Hi @mitkox & @pilebas,

We are aware of this issue and currently working on a fix. We will keep you updated if we find a workaround that we can share before we ship a new version with a fix. 

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @mitkox & @pilebas,

This issue was fixed in the [1.0.266.0](https://github.com/Azure/AKS-Edge/releases/tag/1.0.266.0).

Thanks,
Francisco
