### ISSUE TITLE
[Feedback] Please handle .kube/config  gracefully

### ISSUE THREAD

**Issue by clin4** [Azure/AKS-Edge#165]
**Describe your scenario**
When I create the AKS EE locally, it wipe out all my existing cluster contexts and only keep the newly create local AKS EE.
When I delete the AKS EE locally, it delete the .kube/config

**Feedback**
When I connect to other cluster like normaly AKS,GKE , they just modify my .kube/config file not fully instead of overwirte/delete the whole file.

**Comment by parameshbabu** [comment]
The current product is designed to keep the windows experience simple and clean (export and remove). So, the kubeconfig is exported by default in the default path.
