### ISSUE TITLE
Access Cluster with kubectl from other users

### ISSUE THREAD

**Issue by see-dz** [Azure/AKS-Edge#176]
I noticed that when I log into another user I am unable to see the output for commands such as kubectl get nodes, I assume this is because the AKS edge cluster is deployed on the other accounts' working files. How can I deploy on the local machine opposed of using working files so all users can access?

**Comment by erwinkersten** [comment]
@see-dz for the other users open a powershell session running as Administrator and use the command: `Get-AksEdgeKubeConfig`

**Comment by scooley** [comment]
@see-dz , can I ask why this is coming up for you?  Multiple devs or admins on the same box using local identity for access management?  Happy to jump on a call or similar to learn.
