### ISSUE TITLE
[Question] How to add a Win Server 2019 Worker Node

### ISSUE THREAD

**Issue by ulrichb** [Azure/AKS-Edge#181]
**Describe scenario**

* We need to run Windows Server 2019 containers.
* The current "Windows node files" package (https://aka.ms/aks-edge/windows-node-zip) only contains a Win Server 2022 image.
* So we get _"failed to pull and unpack image "[...]": no match for platform in manifest"_ image pull errors for our Win Server 2019 containers.

**Question**

How can we add a Win Server 2019 worker node?

**Comment by parameshbabu** [comment]
WS 2019 containers are not supported and only WS 2022 supported as experimental feature.

**Comment by ulrichb** [comment]
Okay. Thanks for your reply.
