### ISSUE TITLE
[Feedback] interop-textmsg-consoleapp sample

### ISSUE THREAD

**Issue by jamesyun7** [Azure/AKS-Edge#19]
**Feedback**
Your feedback/comment

Sharing my experience and feedback as below.

1.  typo  : 'name-of-container' should be lowercase

     https://github.com/mitkox/AKS-Edge/blob/main/samples/interop-textmsg-consoleapp/Documentation/Develop%20and%20publish%20the%20Linux%20container.MD#download-and-build-the-container-project
     
      ![image](https://user-images.githubusercontent.com/53162885/207229336-ae230464-bb94-417a-bdc3-caa9ff89612a.png)
     -> docker build -t aksiot.azuecr.io/edgeinterop:latest .

2. Need some comment about pulling image from ACR

 
      option#1) enabling anonymous pulling
      https://learn.microsoft.com/en-us/azure/container-registry/anonymous-pull-access

      option#2) using a Pull Secret
       [Pull images from an Azure container registry to a Kubernetes cluster using a pull secret](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-auth-kubernetes)

3. [step-3-deploy-the-containers-onto-the-aks-edge-edge-device](https://github.com/mitkox/AKS-Edge/blob/main/samples/interop-textmsg-consoleapp/Documentation/DeployContainersOnAKSLiteEdgedevice.md#step-3-deploy-the-containers-onto-the-aks-edge-edge-device)

     command works at 'Charts' Folder
    
     ![image](https://user-images.githubusercontent.com/53162885/207230906-84e83c6a-50fe-4eba-9bde-788fab5997d1.png)

4.  [deploy-the-edge-interop-module](https://github.com/mitkox/AKS-Edge/blob/main/samples/interop-textmsg-consoleapp/Documentation/DeployContainersOnAKSLiteEdgedevice.md#deploy-the-edge-interop-module)

     edgeinterop.yaml -> deployment.yaml
   
    
    Snapshot may helps to see what instruction means the 'internal IP' from kubectl command result
    
     ![image](https://user-images.githubusercontent.com/53162885/207227513-60936944-9251-46d0-91f6-4bbfcb679bef.png)

     ![image](https://user-images.githubusercontent.com/53162885/207227442-6aaea77a-5f03-41cb-89d6-b3efeacf0d54.png)

     need to fill other parameters 

         i.e) 
         env:
           - name: BOOTSTRAP_SERVERS
             value: "192.168.0.4"
           - name: BOOTSTRAP_PORT
             value: "1883"
           - name: CLIENT_ID
             value: "aks-edge-edgeinterop"
           - name: SUBSCRIBE_TOPIC
             value: "sub"
           - name: PUBLISH_TOPIC
             value: "pub"
         imagePullSecrets:
           - name: secret-acr
         

5.  Add NuGet package source setting in option if any issue to publish the CompanionApp

 
![image](https://user-images.githubusercontent.com/53162885/207218487-dc7458db-0a9a-4052-a454-5db30fcdbf05.png)
 

Hopes this feedback helps anyone who might suffer same as me until success!
      
![image](https://user-images.githubusercontent.com/53162885/207227001-dcd6c475-3e39-447e-8f5e-04e7c8c72d8f.png)

**Comment by fcabrera23** [comment]
Hi @jamesyun7,

Thanks for your detailed feedback. We will consider all your raised points to improve the sample documentation.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Added suggestions in [PR 21](https://github.com/Azure/AKS-Edge/pull/21). 

Thanks,
Francisco
