### ISSUE TITLE
[Feature] Support KVM plus nested virtualization in AKS-EE linux node

### ISSUE THREAD

**Issue by gshiva** [Azure/AKS-Edge#190]
**Is your feature request related to a problem? Please describe.**
I cannot use KubeVirt or similar mechanisms to launch VMs using one AKS-EE interface. For VMs, I need to use different provisioning mechanisms such as vCenter or Hyper-V scripts. These two methods of management make it difficult to manage multiple installations.

**Describe the solution you'd like**
I would like the ability to use https://github.com/dockur/windows to launch Windows VMs (or Linux VMs using different mechanism)

**Describe alternatives you've considered**
Alternatives are 
* Terraform + ansible + Hyper-V/vCenter

**Additional context**
If we can mount ZFS volumes for storage for these VMs then we are rockin!

**Comment by parameshbabu** [comment]
AKS EE is designed and supported on Windows Operating systems. Nested virtualization is supported for scenarios using Windows VM. The deployment of the Windows VM itself is not in the scope of this product.
