### ISSUE TITLE
[Feature] AKSEE documentation should outline all ipaddresss ranges used in an installation as part of a network prereq documentation 

### ISSUE THREAD

**Issue by ivanthelad** [Azure/AKS-Edge#198]
**Is your feature request related to a problem? Please describe.**
there, afaik, 3 address ranges that are used by aksee installation. These address ranges should not conflict with any existing ranges on the network  

- AKS nodes, configurable via the Ip4AddressPrefix: **This is documented**
- kubernetes clusterip service range: Performs internal load-balancing using DNAT with iptable : **This is not document**
- Kubernetes POD CNI ip range. **This is not documented**

https://learn.microsoft.com/en-us/azure/aks/hybrid/system-requirements?tabs=allow-table#network-requirements
https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-deployment-config-json

**Describe the solution you'd like**
The Feature request is to document clearly
- the ipaddress range used by kubernetes clusterip service by default and ensure installations do not have overlapping ip ranges with the host network. coupled with notes how to modify these  
- the ipaddress range used by CNI implementation by default and ensure installations do not have overlapping ip ranges with the host network. coupled with notes how to modify these configuration 
- 
**Describe alternatives you've considered**
None, current theres a lag of documentation regarding ip address ranges used by kubernetes 
only thing i can figure out is by referring to the k3s documentation for flannel where it states 
10.42.x.x/16 is used as a range 
https://docs.k3s.io/networking/basic-network-options

this information should be in the aksee docs 
**Additional context**

**Comment by parameshbabu** [comment]
Kubernetes `pod cidr` is `10.42.0.0/16` for K3s and `10.244.0.0/24` for K8s. Kubernetes `service cidr` is `10.43.0.0/16` for K3s and `10.96.0.0/12` for K8s. 
This is added to the docs pages.

**Comment by ivanthelad** [comment]
thank you . i checked the docs https://learn.microsoft.com/en-us/azure/aks/hybrid/system-requirements?tabs=allow-table#network-requirements are i do not see a change. i guess they will land soon

**Comment by parameshbabu** [comment]
https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-concept-networking#networking-by-deployment-type is where the content is added. The other link is for related product, not AKS EE.
