### ISSUE TITLE
Where is the download for the Windows node files?

### ISSUE THREAD

**Issue by m3748** [Azure/AKS-Edge#199]
I am trying to set up a cluster with a Windows node. I am following the steps on this website to download the artifacts: https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine. It references Windows node files, but I do not see a link to download them. Where can I get them?

**Comment by haodeon** [comment]
https://aka.ms/aks-edge/windows-node-zip

**Comment by parameshbabu** [comment]
https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine#install-aks-edge-essentials , step 3 does call out how to add this. 
`msiexec.exe /i AksEdge-kXs-x.x.xxx.x.msi ADDLOCAL=CoreFeature,WindowsNodeFeature`

**Comment by m3748** [comment]
Shouldn’t the link to download the windows files be on that page? Am I
missing it?
