### ISSUE TITLE
[BUG] AKS Arc agent connection fails with timeout (aad-proxy)

### ISSUE THREAD

**Issue by mitkox** [Azure/AKS-Edge#20]
**Describe the bug**
The Arc agent for AKS is not connecting through a proxy. The Arc-connected machine agent is connected on the same machine and works fine. 

**To Reproduce**
1. Configure proxy in the config file 
2. Connect-AideArc exits with an error when trying the connect the AKS Arc agent 
WARNING: Unable to fetch the Object ID of the Azure AD application used by Azure Arc service. Unable to enable the 'custom-locations' feature. Insufficient privileges to complete the operation.
WARNING: Please check if the azure-arc namespace was deployed and run 'kubectl get pods -n azure-arc' to check if all the pods are in running state. A possible cause for pods stuck in pending state could be insufficient resources on the kubernetes cluster to onboard to arc.
ERROR: Unable to install helm release: Error: timed out waiting for the condition Error: arc connect failed.
False

**Expected behavior**
AKS Arc agent to connect through a proxy 

**Screenshots**

**Environment (please complete the following information):**
 - AKS Edge Essentials Version 0.7.22335.1024
 - Kubernetes version 1.23.6
 - Windows Host OS (please complete the following information):
    - Edition: Windows 10 Enterprise
    - Version: 19044
    - Virtual Machine: PC

**Additional context**
The helm or the Arc agent for AKS EE is not reading the proxy configuration

**Comment by parameshbabu** [comment]
https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/troubleshooting#helm-timeout-error
states 
![image](https://user-images.githubusercontent.com/16312352/207422003-ef21da5f-f62d-498d-a29f-2379071c6ef4.png)

**Comment by dnarh** [comment]
I get the same error when trying to connect a multi-node deployment to Arc. If I connect the deployment to Arc with only one node, before scaling out to the remaining nodes, which is then done after Arc connection has succeeded, it works.

**Comment by krdhruva** [comment]
@dnarh, can you pls confirm whether `clusterconnect-agent` and `config-agent` pods are running? 
Additionally, can you follow this and share the output?
https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/diagnose-connection-issues#connections-with-a-proxy-server

**Comment by parameshbabu** [comment]
Fixed with #70  and GA updates (Az ConnectedKubernetes 0.8.0 version)
