### ISSUE TITLE
[Question] new-aksedgeDeployment cannot find the source code, is it open src or closed src?

### ISSUE THREAD

**Issue by mqttBridge** [Azure/AKS-Edge#207]
**Describe scenario**
i want to understand under the hood details of "new-aksedgedeployment" cmdlet? 

**Question**
i want to understand under the hood details of "new-aksedgedeployment" cmdlet?pls share the relevant git hub repo

**Comment by scholz** [comment]
Hi @mqttBridge , just chiming in:

core AKSEE powershell functions are delivered through AKSEE MSI installer. They are usually in : "C:\Program Files\WindowsPowerShell\Modules\AksEdge\<AKSEE Version>" (e.g. 1.6.384.0 for an older version of AKSEE)

E.g. the specific function you seek is in AksEdge.psm1 .

**Comment by mqttBridge** [comment]
thanks for the response, but i can only see the function being invoked but not the function definition in aksedge.psm1 file.
i also did a git repo level search for this function definition "new-aksedgedeployement"

regrards

**Comment by scholz** [comment]
Ok strange. in the version iam refering to i find the function definition in the mentioned file and can also see that it calls NewDeploymentInternal... **Maybe we are not talking about the same thing: iam refering to the official installer you can download from here: https://aka.ms/aks-edge/k3s-msi** . if you install this or maybe extract the files from msi - if possible. Then you will find the mentioned file and the code inside. Also: as far as i understand, this repository here is just an auxillary repo which does not contain this part of the code.

**Comment by mqttBridge** [comment]
Thanks scholz your comment helped, as u hv told i can find it only when i install. possible to share the git repo of  k3s-msi?

**Comment by mqttBridge** [comment]
Hi scholz

Possible to share the git repository of msi installer if it is open src?

Regards

**Comment by scholz** [comment]
Hi @mqttBridge , i am just a user of AKSEE and cannot comment on the code availability or the nature of its license. But AFAIK the code is not in an open github repo.

**Comment by parameshbabu** [comment]
the module is deployed as part of the msi deployment and the msi source code is not open sourced. Thanks.
