### ISSUE TITLE
[BUG] IP Address Config mis-match

### ISSUE THREAD

**Issue by colinrippeyfinarne** [Azure/AKS-Edge#25]
**Describe the bug**
                                                                                                                                                                                  - Waiting for Kubernetes node (win-3a62p20kjqp-ledge) to reach condition Ready, timeout = 900 seconds                                                                           WARNING: Waiting for node (win-3a62p20kjqp-ledge) timed out.                                                                                                                      - Error: Linux node not in Ready state, or cluster could not be reached from host side at line 3140

**To Reproduce**

I have tried to the follow the steps to create a single machine deployment here:

https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-single-node-deployment

My aksedge-config.json file is as follows:

{
    "SchemaVersion": "1.1",
    "Version": "1.0",
    "DeployOptions": {
        "ControlPlane": false,
        "Headless": false,
        "JoinCluster": false,
        "NetworkPlugin": "flannel",
        "SingleMachineCluster": true,
        "TimeoutSeconds": 900,
        "NodeType": "Linux",
        "ServerTLSBootstrap": true
    },
    "EndUser": {
        "AcceptEula": true,
        "AcceptOptionalTelemetry": false
    },
    "LinuxVm": {
        "CpuCount": 4,
        "MemoryInMB": 8192,
        "DataSizeinGB": 20,
        "Ip4Address": "10.0.0.100"
    },
    "Network": {
        "VSwitch": {
            "Name": "NestedHost",
            "Type": "External",
            "AdapterName": "Ethernet"
        },
        "ControlPlaneEndpointIp": "10.0.0.101",
        "Ip4GatewayAddress": "10.0.0.1",
        "Ip4PrefixLength": 24,
        "ServiceIPRangeSize": 0,
        "ServiceIPRangeStart": "10.0.0.111",
        "ServiceIPRangeEnd": "10.0.0.130",
        "DnsServers": [
            "10.0.0.1"
        ],
        "InternetDisabled": false,
        "Proxy": {
            "Http": "",
            "Https": "",
            "No": ""
        }
    }
}

I am running the deployment on the following stack:

Windows 10 22H2 (OS Build 19045.2364)
Hosting a Hyver-V VM as follows:
Windows Server 2022 21H2 (OS Build 20348.587)
I am using nested virtualization

The Windows 10 host has a WiFi connection that gets the following:
IP: 10..0.0.21
Gateway: 10.0.0.1
Hyper-V switch for Windows Server 2022 VM is set to External using the host WiFi

The Windows Server 2022 IP is:
IP: 10.0.0.22
Gateway: 10.0.0.1
(nested) Hyper-V switch for child VMs is External using Microsoft Hyper-V Network Adapter

This is why I have entered the above IP details in the aksedge-config.json.

As I run the New-AksEdgeDeployment commandlet I see the following outputs:

[12/17/2022 15:05:19] Creating single machine cluster vmms network

 - AksEdge - private network carved:

Name  : ip4GatewayAddress
Value : 192.168.0.1

Name  : WindowsVmIp4Address
Value : 192.168.0.3

Name  : LinuxVmIp4Address
Value : 192.168.0.2

Name  : ip4Subnet
Value : 192.168.0.0

Name  : ip4PrefixLength
Value : 24

 - Determining DNS servers capable of resolving the endpoint 'microsoft.com' from the list of potential servers (10.0.0.1)...
 - Success, one or more eligible DNS servers found (10.0.0.1)...

[12/17/2022 15:05:26] Deploying AKS Edge Essentials - K3s (Public Preview)

So I am either missing some additional config in the aksedge-config.json or the AksEdge - private network carved step is ignoring my entries.

**Comment by parameshbabu** [comment]
on a single machine deployment (SingleMachineCluster=true), the ip configs are ignored as it creates an internal network and assigns static ips automatically.

However, the timeout error is certainly an issue that we need to investigate.

**Comment by colinrippeyfinarne** [comment]
> on a single machine deployment (SingleMachineCluster=true), the ip configs are ignored as it creates an internal network and assigns static ips automatically.
> 
> However, the timeout error is certainly an issue that we need to investigate.

Ok thanks for the reply. How can I help diagnose the issue? I can supply the logs, and apologies I should have detailed I am using the k3s install.

Trying to grok the powershell I can see lower level commands being executed to test if the cluster is up and running, as I await the script timing out I was thinking I could have a separate powershell window loaded that I could run some commands against?

**Comment by parameshbabu** [comment]
Yes, can you check if you are able to open another AksEdgeShell (double click on the AksEdgeShell.cmd) and type 'mars' that should take you into the linux vm prompt. Run 'kubectl get nodes' inside the linux vm and see if the node state is ready. If this is the case, then i suspect there are firewall rules in Windows Server VM blocking access to the nested linux vm

**Comment by colinrippeyfinarne** [comment]
I've been able to get my local k3s cluster up and running by completely removing the Network sections:

"Network": {
"VSwitch": {
"Name": "",
"Type": "",
"AdapterName": ""
},

I might return to this config another time to see if adding entries that relate to my specific Hyper-V environment work but for now I can at least work with my local k3s cluster.

I've also got some feedback on the RAM config of my env and what values I use that successfully complete the Create single machine deployment steps, but I feel this feedback should be added to a separate issue.
