### ISSUE TITLE
[Feedback] Log improvement: Line 3128 error

### ISSUE THREAD

**Issue by xiongyu0523** [Azure/AKS-Edge#27]
**Describe your scenario**
User will get an error prompt ` - Starting Kubernetes runtime in Linux node failed, see details in the event log at line 3128` when they are provisioning the worker node and if there is any issue with network configuration or network (e.g. master node is disconnected), the deployment will fail and show this log. 

**Feedback**
The log does not tell the problem and does not tell which file the user should look into to check the issue. I tried to check all logs in the ZIP, but I can't find any useful information there. It's better to improve this log so users can easily understand how to troubleshoot

**Comment by fcabrera23** [comment]
Hi @xiongyu0523,

Thanks for your feedback. We will take it into account for our next documentation refresh. Also, as part of the latest [1.0.266.0](https://github.com/Azure/AKS-Edge/releases/tag/1.0.266.0) update, we've improved our logs and error messaging. 

Thanks,

**Comment by fcabrera23** [comment]
Hi @xiongyu0523,

We have a new [AKS Edge Essentials logs](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-resources-logs) guide. We will create troubleshooting guides in the upcoming weeks. 

Thanks,
Francisco
