### ISSUE TITLE
[Question] Can AKS EE full deployment works with two local hyper-v VM?

### ISSUE THREAD

**Issue by xiongyu0523** [Azure/AKS-Edge#28]
**Describe scenario**
I was trying to create two hyper-V VM on my machine and connect them over External Switch. On the first node, I deploy a full deployment, and it works. On the second node, I configure it to be a worker node, but it seems deployment can't be finished and show a `- Starting Kubernetes runtime in Linux node failed, see details in the event log at line 3128`  error. I tried both Flannel and Calico with K8S. 

Full static configuration
Router/Gateway: 192.168.0.1
My PC: 192.168.0.10
Windows VM1: 192.168.0.11
Windows VM2: 192.168.0.12
Master node Linux: 192.168.0.50
Control Plane Endpoint IP: 192.168.0.52
Service IP: 192.168.0.60 - 192.168.0.69
Worker node Linux: 192.168.0.51

**Question**
Is it a supported scenario? If it is, I can provide my logs and request for troubleshoot

**Comment by parameshbabu** [comment]
we do not support this scenario. On a windows host machine, we support atmost 1 linux VM and 1 windows VM for the AKS EE configuration. If you need multiple linux VMs, we recommend you AKS-HCI solution. https://learn.microsoft.com/en-us/azure/aks/hybrid/overview

**Comment by xiongyu0523** [comment]
@parameshbabu 

I want to clarify a little bit, this is not a AKS-HCI case. This setup is try to run a multiple node setup on a single machine using nested virtualizaiton. So people can try AKS Edge Full deployment without need two physical machines. 

1. Create two hyper-v Windows machines, connect them to the same External Virtual Switch and setup static IP addresses in the same scope of host machine under home router. They can communicate with each other without a problem. 
2. On first windows VM, create a fully depolyment, it works well
3. On the second windows, I can't successfuly create a worker node add to the cluster.

It looks like this:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/20612136/210293625-3448cf69-6d63-4f6d-87a3-26d44d8b5312.png)

**Comment by parameshbabu** [comment]
@xiongyu0523 This should work if you have configured your ip ranges of your external switch properly. I would use an internal switch at the Host Windows machine with its own Nat so that the ip addressess of the VMs and the linux VMs are in the same range and bound to the machine (isolated and not accessible from outside)
