### ISSUE TITLE
[Feedback]Doc improvement: Linux VM IP is different in two places of the diagram.

### ISSUE THREAD

**Issue by xiongyu0523** [Azure/AKS-Edge#30]
**Describe your scenario**
In [AKS Edge Essentials key concepts](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-concept), Linux VM IP address is different in two places of the diagram.

![networking-single](https://user-images.githubusercontent.com/20612136/208356998-21b9b321-a66b-4225-9ec7-a1f1e30bac64.png)

**Feedback**
Your feedback/comment

**Comment by parameshbabu** [comment]
Thanks for calling this out. We will fix the picture.
