### ISSUE TITLE
[Question] AKS Edge run on baremetal/linux

### ISSUE THREAD

**Issue by xzrian** [Azure/AKS-Edge#31]
AKS-Edge meant to run on hardware or IOT device that has minimal or sufficient amount of RAM.
I saw that one of the requirmeent is to use Windows Server or Windows 10 IOT.
Is there roadmap indicate that AKS-Edge run on the baremetal/hardware itself instead of running on Windows as a guest host?

**Comment by rcheeran** [comment]
Not at the moment @xzrian! We will be launching our GA on Windows only for now.
