### ISSUE TITLE
[Feedback] "Connect to ARC" page misses Microsoft.ExtendedLocation & ...PolicyInsights resource provider as pre-req

### ISSUE THREAD

**Issue by JuergenSchwertl** [Azure/AKS-Edge#37]
["Connect to ARC : Chapter 1"](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-connect-to-arc#1-configure-your-azure-environment) lists to check:

> Enable all required resource providers in the Azure subscription such as 
> Microsoft.HybridCompute, Microsoft.GuestConfiguration,
> Microsoft.HybridConnectivity, Microsoft.Kubernetes, and
> Microsoft.KubernetesConfiguration.

[AksEdgeAzureSetup.ps1 :: Line 232](https://github.com/Azure/AKS-Edge/blob/main/tools/scripts/AksEdgeAzureSetup/AksEdgeAzureSetup.ps1#L231)
though also registers "Microsoft.ExtendedLocation".

[Initialize-AideARC (respectively RPNamespaces in AksEdge-ARC.ps1 :: Line 19](https://github.com/Azure/AKS-Edge/blob/main/tools/modules/AksEdgeDeploy/AksEdge-Arc.ps1#L19) then also registers "Microsoft.PolicyInsights"

**Feedback**
Chapter should ideally list all required resource providers, i.e.
> Enable all required resource providers in the Azure subscription such as 
> **Microsoft.HybridCompute**, **Microsoft.GuestConfiguration**,
> **Microsoft.HybridConnectivity**, **Microsoft.Kubernetes**,
> **Microsoft.KubernetesConfiguration**, **Microsoft.ExtendedLocation** and
> **Microsoft.PolicyInsights**.

**Comment by parameshbabu** [comment]
Noted. ExtendedLocation and PolicyInsights are optional resource providers - required only when you start using those features (custom location and Policy). Will see how to make that optional resource providers visible for users.
