### ISSUE TITLE
[BUG] AksEdgeAzureSetup.ps1 and Initialize-AideARC should fail if Location is unsupported

### ISSUE THREAD

**Issue by JuergenSchwertl** [Azure/AKS-Edge#38]
**Describe the bug**
If you set Azure.Location in aide-userconfig.json to an unsupported region for connected cluster (i.e. "GermanyWestCentral")
**AksEdgeAzureSetup.ps1** & **Initialize-AideARC** don't indicate any issues with the aide-userconfig
**Connect-AideARC** then fails with error
`ERROR: Connected cluster resource creation is supported only in the following locations: westeurope, eastus, westcentralus, southcentralus, southeastasia, uksouth, eastus2, westus2, australiaeast, northeurope, francecentral, centralus, westus, northcentralus, koreacentral, japaneast, eastasia, westus3, canadacentral, eastus2euap
Use the --location flag to specify one of these locations.
Error: arc connect failed.`    

**To Reproduce**

> PS C:\Repos\Azure\AKS-Edge\tools> **Initialize-AideArc**
> 
> Azure configuration:
> @{SubscriptionName=(jschwert-hotmail) Visual Studio Enterprise Subscription; 
>  SubscriptionId=14b9d879-5858-4041-9351-c5eef21f59fc;
>  TenantId=740b9bab-bfcc-4140-8a6f-414abf7bc8fc;
>  ResourceGroupName=Aks-Edge-RG;
>  ServicePrincipalName=aks-edge-essentials-sp;
>  **_Location=GermanyWestCentral_**;
>  Auth=}

> 
>  **Azure CLI installed**
> Installing az extension connectedmachine
> Installing az extension connectedk8s
> Installing az extension customlocation
> Installing az extension k8s-extension
>  Checking azure-cli-core minVersion 2.41.0..found 2.43.0
>  Checking k8s-extension minVersion 1.3.3..found 1.3.7
>  Checking customlocation minVersion 0.1.3..found 0.1.3
>  Checking connectedk8s minVersion 1.3.1..found 1.3.6
>  Checking connectedmachine minVersion 0.5.1..found 0.5.1
>  Checking azure-cli minVersion 2.41.0..found 2.43.0
> Using service principal id to login
> Logged in (jschwert-hotmail) Visual Studio Enterprise Subscription subscription as d60ff4a9-9ca0-440e-b028-fd9ca34d763d (servicePrincipal)
> Roles enabled for this account are:
> Contributor for scope /subscriptions/14b9d879-5858-4041-9351-c5eef21f59fc/resourceGroups/Aks-Edge-RG
> Checking Aks-Edge-RG...
> * Aks-Edge-RG exists
> Checking Microsoft.HybridCompute...
> * Microsoft.HybridCompute provider registered
> Checking Microsoft.GuestConfiguration...
> * Microsoft.GuestConfiguration provider registered
> Checking Microsoft.HybridConnectivity...
> * Microsoft.HybridConnectivity provider registered
> Checking Microsoft.Kubernetes...
> * Microsoft.Kubernetes provider registered
> Checking Microsoft.KubernetesConfiguration...
> * Microsoft.KubernetesConfiguration provider registered
> Checking Microsoft.ExtendedLocation...
> * Microsoft.ExtendedLocation provider registered
> Checking Microsoft.PolicyInsights...
> * Microsoft.PolicyInsights provider registered
> Initialize-AideArc successful.
> True
> 
> 
> PS C:\Repos\Azure\AKS-Edge\tools> **Connect-AideArc**
> Connecting Azure Arc-enabled Server..
> ConnectedMachineAgent is not installed
> **Installing ConnectedMachineAgent...**
> VERBOSE: Installing Azure Connected Machine Agent
> VERBOSE: Total Physical Memory:     65.239 MB
> VERBOSE: .NET Framework version: 4.8.9032
> VERBOSE: Downloading agent package from https://aka.ms/AzureConnectedMachineAgent to C:\Users\jschwert\AppData\Local\Temp\AzureConnectedMachineAgent.msi
> VERBOSE: Installing agent package
> Installation of azcmagent completed successfully
> Setting up auto update via Microsoft Update
> **ConnectedMachineAgent is installed successfully**
> ConnectedMachine Agent state is Disconnected. Connecting now...
> js-ms-p1-k3s is not connected to Arc
> ConnectedMachineAgent connected.
> Connecting Azure Arc-enabled Kubernetes..
> Updating kubeconfig file with Get-AksEdgeKubeConfig...
> Establishing Azure Connected Kubernetes for js-ms-p1-k3s
> WARNING: This operation might take a while...
> 
> WARNING: Downloading helm client for first time. This can take few minutes...
> **ERROR: Connected cluster resource creation is supported only in the following locations: westeurope, eastus, westcentralus, southcentralus, southeastasia, uksouth, eastus2, westus2, australiaeast, northeurope, francecentral, centralus, westus, northcentralus, koreacentral, japaneast, eastasia, westus3, canadacentral, eastus2euap**
> Use the --location flag to specify one of these locations.
> **Error: arc connect failed.**
> False

**Expected behavior**
Setup and/or Initialization should already indicate that current config is not  supported.

**Environment :**
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

Loading AksEdgeDeploy module from C:\Repos\Azure\AKS-Edge\tools\modules..
Hyper-V is enabled
HostOS  : Microsoft Windows 11 Enterprise(4)
Version : 10.0.22621.963
Lang    : en-US de-DE en-GB
Name    : JS-MS-P1
Total CPUs              : 16
Free RAM / Total RAM    : 44 GB / 64 GB
Free Disk / Total Disk  : 710 GB / 952 GB
AKS Edge Essentials - K3s (Public Preview) 0.7.22335.1024 is installed.
Loading AksEdge module..
AksEdge version         : 0.7.22335.1024
AksEdgeShell  version   : 1.0.221212.1200
AksEdgeDeploy version   : 1.0.221212.1200

Windows PowerShell:
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by JuergenSchwertl** [comment]
After creating a new resource group in a supported region afterwards (and updating aide-userconfig.json accordingly)
.\scripts\AksEdgeAzureSetup\AksEdgeAzureSetup.ps1 .\aide-userconfig.json -spContributorRole   **succeeds**
Initialize-AideArc **fails** with error

> ERROR: Operation returned an invalid status 'Forbidden'
> Error: Aks-Edge-WE-RG not found

AksEdgeAzureSetup apparently doesn't realize the enabled role for service principal is for obsolete resource group and does not enable role on new resource group
> **Checking Aks-Edge-WE-RG...**
> **_Aks-Edge-WE-RG_ exists**

...

> aks-edge-essentials-sp is already present.
> Roles enabled for this account are:
> Contributor for scope /subscriptions/14b9d879-5858-4041-9351-c5eef21f59fc/resourceGroups/**_Aks-Edge-RG_**


**Complete output**

> PS C:\Repos\Azure\AKS-Edge\tools> **.\scripts\AksEdgeAzureSetup\AksEdgeAzureSetup.ps1 .\aide-userconfig.json -spContributorRole**
> AksEdgeAzureSetup version       : 1.0.221208.0900
>  Azure CLI installed
>  Checking azure-cli-core minVersion 2.41.0..found 2.43.0
>  Checking azure-cli minVersion 2.41.0..found 2.43.0
> @{SubscriptionName=(jschwert-hotmail) Visual Studio Enterprise Subscription; 
> SubscriptionId=14b9d879-5858-4041-9351-c5eef21f59fc; 
> TenantId=740b9bab-bfcc-4140-8a6f-414abf7bc8fc; 
> **ResourceGroupName=Aks-Edge-WE-RG**;
> ServicePrincipalName=aks-edge-essentials-sp;
> **Location=WestEurope**;
> Auth=}
> az login to create/update service principal
> WARNING: A web browser has been opened at https://login.microsoftonline.com/740b9bab-bfcc-4140-8a6f-414abf7bc8fc/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
> Logged in (jschwert-hotmail) Visual Studio Enterprise Subscription subscription as jschwert@hotmail.com (user)
> TenantID       : 740b9bab-bfcc-4140-8a6f-414abf7bc8fc
> SubscriptionId : 14b9d879-5858-4041-9351-c5eef21f59fc
> User Principal Name : jschwert_hotmail.com#EXT#@jschwerthotmail.onmicrosoft.com
> Looking for Azure RBAC roles
> Roles enabled for this account are:
> Owner for scope /subscriptions/14b9d879-5858-4041-9351-c5eef21f59fc/resourcegroups/Azure-Sphere-RG/providers/Microsoft.AzureSphere/catalogs/JSchwertHotmail_Catalog
> User Access Administrator for scope /
> Looking for classic administrator roles
> Roles enabled for this account are:
> ServiceAdministrator;AccountAdministrator for scope /subscriptions/14b9d879-5858-4041-9351-c5eef21f59fc
> * You have sufficient privileges
> **Checking Aks-Edge-WE-RG...**
> ** * Aks-Edge-WE-RG exists**
> Checking Microsoft.HybridCompute...
> * Microsoft.HybridCompute provider registered
> Checking Microsoft.GuestConfiguration...
> * Microsoft.GuestConfiguration provider registered
> Checking Microsoft.HybridConnectivity...
> * Microsoft.HybridConnectivity provider registered
> Checking Microsoft.Kubernetes...
> * Microsoft.Kubernetes provider registered
> Checking Microsoft.KubernetesConfiguration...
> * Microsoft.KubernetesConfiguration provider registered
> Checking Microsoft.ExtendedLocation...
> * Microsoft.ExtendedLocation provider registered
> aks-edge-essentials-sp is already present.
> Roles enabled for this account are:
> Contributor for scope /subscriptions/14b9d879-5858-4041-9351-c5eef21f59fc/resourceGroups/**_Aks-Edge-RG_**
> Use existing password for aks-edge-essentials-sp in Auth.Password field
> ServicePrincipalId for aks-edge-essentials-sp is d60ff4a9-9ca0-440e-b028-fd9ca34d763d
>
> PS C:\Repos\Azure\AKS-Edge\tools> **Read-AideUserConfig**
> True
>
> PS C:\Repos\Azure\AKS-Edge\tools> **Get-AideUserConfig**
> 
> 
> SchemaVersion     : 1.0
> Version           : 1.0
> AksEdgeProduct    : AKS Edge Essentials - K3s (Public Preview)
> AksEdgeProductUrl :
> InstallOptions    : @{InstallPath=; VhdxPath=}
> Azure             : @{SubscriptionName=(jschwert-hotmail) Visual Studio Enterprise Subscription; SubscriptionId=14b9d879-5858-4041-9351-c5eef21f59fc;
>                     TenantId=740b9bab-bfcc-4140-8a6f-414abf7bc8fc; **ResourceGroupName=Aks-Edge-WE-RG**; ServicePrincipalName=aks-edge-essentials-sp; **Location=WestEurope**;
>                     Auth=}
> AksEdgeConfigFile : aksedge-config.json
> AksEdgeConfig     : @{SchemaVersion=1.1; Version=1.0; DeployOptions=; EndUser=; LinuxVm=; Network=}
> 
> 
> 
> PS C:\Repos\Azure\AKS-Edge\tools> Initialize-AideArc
> Azure configuration:
> @{SubscriptionName=(jschwert-hotmail) Visual Studio Enterprise Subscription; SubscriptionId=14b9d879-5858-4041-9351-c5eef21f59fc; TenantId=740b9bab-bfcc-4140-8a6f-414abf7bc8fc; ResourceGroupName=Aks-Edge-WE-RG; ServicePrincipalName=aks-edge-essentials-sp; Location=WestEurope; Auth=}
>  Azure CLI installed
>  az extension connectedmachine installed
>  az extension connectedk8s installed
>  az extension customlocation installed
>  az extension k8s-extension installed
>  Checking azure-cli-core minVersion 2.41.0..found 2.43.0
>  Checking k8s-extension minVersion 1.3.3..found 1.3.7
>  Checking customlocation minVersion 0.1.3..found 0.1.3
>  Checking connectedk8s minVersion 1.3.1..found 1.3.6
>  Checking connectedmachine minVersion 0.5.1..found 0.5.1
>  Checking azure-cli minVersion 2.41.0..found 2.43.0
> Using service principal id to login
> Logged in (jschwert-hotmail) Visual Studio Enterprise Subscription subscription as d60ff4a9-9ca0-440e-b028-fd9ca34d763d (servicePrincipal)
> Roles enabled for this account are:
> Contributor for scope /subscriptions/14b9d879-5858-4041-9351-c5eef21f59fc/resourceGroups/Aks-Edge-RG
> **_Checking Aks-Edge-WE-RG..._**
> **_ERROR: Operation returned an invalid status 'Forbidden'_**
> **_Error: Aks-Edge-WE-RG not found_**
> Checking Microsoft.HybridCompute...
> * Microsoft.HybridCompute provider registered
> Checking Microsoft.GuestConfiguration...
> * Microsoft.GuestConfiguration provider registered
> Checking Microsoft.HybridConnectivity...
> * Microsoft.HybridConnectivity provider registered
> Checking Microsoft.Kubernetes...
> * Microsoft.Kubernetes provider registered
> Checking Microsoft.KubernetesConfiguration...
> * Microsoft.KubernetesConfiguration provider registered
> Checking Microsoft.ExtendedLocation...
> * Microsoft.ExtendedLocation provider registered
> Checking Microsoft.PolicyInsights...
> * Microsoft.PolicyInsights provider registered
> **_Initialize-AideArc failed._**
> False
>

**Comment by parameshbabu** [comment]
Good catch. Will investigate how to get this list programmatically to avoid hardcoding.
