### ISSUE TITLE
Allow container images to be loaded from archives

### ISSUE THREAD

**Issue by dancingCamel** [Azure/AKS-Edge#40]
In other kubernetes systems we have the to option to load images from archives (such as .tar files exported by docker). 
e.g. In KinD we can use "kind load image-archive" and in microk8s there is "microk8s images import".
If we want to create a single deployable bundle to a location then we should be able to load images from archive files. 

I would like to have a similar command for AKS-Edge e.g. Import-AksEdgeImage

**Comment by dancingCamel** [comment]
Also, while there isn't a command for doing so, is there another way to load the images, like scp the file into the edge VM and use ctr image import from inside the VM itself?
I tried to find the edge VM with hyper v but couldn't find it, and I tried to ssh into the vm using the IP found at Get-AksEdgeNodeAddr.
This didn't work as I didn't have credentials, and password authentication is disabled on the VM (according to Invoke-AksEdgeNodeCommand -Command "sudo cat /etc/ssh/sshd_config") 
I tried to create an ssh key with the invoke command but it just hangs.

**Comment by fcabrera23** [comment]
Hi @dancingCamel,

Thanks for reaching out.  We are using SSH over Hyper-V sockets, so normal SSH/SCP won't work. For more information, see #41.  We are currently investigating exposing a new PS cmdlet to copy files from/to the Linux/Windows nodes.  Once you copied the files, you can use the `Invoke-AksEdgeNodeCommand` to finalize the import. 

Please check our [AKS Edge PS](https://learn.microsoft.com/en-us/azure/aks/hybrid/reference/aks-edge-ps/) in the upcoming updates to get more information.

Thanks,
Francisco

**Comment by dancingCamel** [comment]
That's great. 
I'll keep an eye on the updates.

Thanks,
Robert

**Comment by fcabrera23** [comment]
Hi @dancingCamel 

This issue was fixed in the [1.0.266.0](https://github.com/Azure/AKS-Edge/releases/tag/1.0.266.0) update. Now you can use the `Copy-AksEdgeNodeFile` and the `Invoke-AksEdgeNodeCommand` to achieve your scenario.

Thanks,
Francisco
