### ISSUE TITLE
How to ssh in to aks-edge linux node ?

### ISSUE THREAD

**Issue by githubYasser** [Azure/AKS-Edge#41]
**Describe scenario**
I'm using aks-edge single machine installer.
I installed aks edge on my windows machine and i also created the kubernetes cluster (with one linux node).

**Question**
How can one ssh to the linux node ?
Does aks-edge creates some new ssh keys during installation ? if yes, where is the private-key stored ?

Thanks for your support.

yasser

**Comment by githubYasser** [comment]
My  CBL-Mariner/Linux node does not have an EXTERNAL-IP ! I tried ssh with the INTERAL-IP and that didn't work.

**Comment by fcabrera23** [comment]
Hi @githubYasser,

Thanks for reaching out.  There are different ways to interact with the Linux node VM.  

We generally recommend using the [Invoke-AksEdgeNodeCommand](https://learn.microsoft.com/en-us/azure/aks/hybrid/reference/aks-edge-ps/invoke-aksedgenodecommand), to execute Linux bash commands inside the VM directly from PowerShell.

However, if you want to establish an SSH interactive session, you can do it by running the `AksEdgePrompt.cmd` or the `AksEdgePrompt-PS7.cmd`  under [tools](https://github.com/Azure/AKS-Edge/tree/main/tools) and after the PS session is loaded, run the `mars` cmdlet.  

All SSH keys are created during the node creation and stored under a protected folder. Keep in mind that for security reasons we are using a Hyper-V socket to establish the communication, so normal SSH over port 22 won't work.  Hyper-V sockets are a special type of socket that can only be created between the host OS and the guest OS and enables a secure channel without the need for the normal network channel.

Finally, regarding your last IP question, by default, we use an Internal virtual switch to communicate between the Windows host OS and the Windows/Linux nodes. If you want to have an External IP, you will need to deploy the nodes using an external virtual switch. 

Thanks,
Francisco
