### ISSUE TITLE
[Question] How to configure the DNS names and TLS Settings

### ISSUE THREAD

**Issue by Danielku15** [Azure/AKS-Edge#42]
**Describe scenario**
I have a AKS Edge Single Machine Deployment (K8S) on a Root Server and used NAT with port forwarding to make things accessible from the outside. Now we want to buy a domain to make services available through the usual subdomain patterns. The K8S CA Certificate which is auto configured in AKS Edge is only valid for some local IPs (not even the public one) and this leads to errors like:

> Unable to connect to the server: x509: certificate is valid for 10.96.0.1, 192.168.0.2, not xxx.xxx.xxx.xxx

**Question**
Is there an AKS Edge specific/compatible way to tell the cluster about the public IP and domains pointing to it so that the TLS certificate and other configurations come correctly out-of-the-box? I know that I can also "simply" exchange the certficates after the cluster is deployed though `kubectl` but as there is already some bootstrapping and configuring done during deployment I was wondering if we can directly make this part of the deployment process.

That would also keep things a lot easier for us when we would need to destroy and recreate the cluster if we could supply such settings already in the `aksedge-config.json`. Maybe even a custom real TLS certificate could be supplied?

**Comment by fcabrera23** [comment]
Hi @Danielku15,

Thanks for reaching out. As part of the [1.0.266.0](https://github.com/Azure/AKS-Edge/releases/tag/1.0.266.0) update we removed the support for TLS bootstrapping.  We expect to work on this feature in the upcoming months to provide a better user experience and broader support for TLS.  

Also, your feedback is super useful, so we'd love to set up some time to discuss your scenario and understand how we can improve our product. 

Thanks,
Francisco
