### ISSUE TITLE
[Question] Exposing services in single-machine cluster

### ISSUE THREAD

**Issue by dnarh** [Azure/AKS-Edge#48]
**Describe scenario**
Running a single-machine AKS Edge k3s cluster on a Intel i7-based machine running Windows 10, connected to Azure Arc. 

**Question**
Is an external load balancer required for exposing services to the network? Currently, when setting up services as load balancer, the external IPs allocated are on subnet 192.168.0.x, which I assume are for the internal (cluster) network, while the network interface of the machine is connected to subnet 192.168.150.x.

**Comment by fcabrera23** [comment]
Hi @dnarh,

Thanks for reaching out.  Your current understanding is correct, and when you use the default networking options (using an Internal virtual switch),  services will be exposed to the internal network and not accessible by external devices. 

There are two alternatives to access services from external devices:

1. Keep the Internal Switch configuration and static IP deployments/services and then use port forwarding to that static IP. For example, imagine your services has the 192.168.0.20 address, and you want to forward the port 8080, then on the Windows host OS you should run the following command: `netsh interface portproxy add v4tov4 listenport=8080 listenaddress=0.0.0.0 connectport=8080 connectaddress=192.168.0.20`. For more information, check https://learn.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy.

2. Deployment using an External virtual switch. When deploying the AKS EE single-node cluster, use an external virtual switch. When doing this, your node will connect to your external network and services will be exposed to external devices. 

Hope this helps. 
Thanks,
Francisco

**Comment by dnarh** [comment]
Thanks for the reply @fcabrera23.

Alternative 1 works. However, doing this means that all external IPs in the cluster will have to be forwarded to the IP of the host. 
Therefore, alternative 2 seems like the better option, but when trying to deploy a single-node cluster with an external virtual switch, I end up with the same error as #25.

**Comment by fcabrera23** [comment]
Hi @dnarh,

Sorry, I had to update my response as I forgot to mention that for the external switch you need to create a scalableCluster and keep it to one single node, instead of singleNode cluster. 

Thanks,
Francisco
