### ISSUE TITLE
[BUG] InvalidSubscriptionId when connecting to Arc

### ISSUE THREAD

**Issue by dnarh** [Azure/AKS-Edge#49]
**Describe the bug**
I followed the [How-to](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine) for AKS Edge, setting up a full k3s deployment and connecting to Arc. When waiting for the `Connect-AideArc` command to finish, the following error occurred:

> PS C:\Downloads\AKS-Edge-main\AKS-Edge-main\tools> Connect-AideArc
> Connecting Azure Arc-enabled Server..
> ConnectedMachineAgent is not installed
\> Installing ConnectedMachineAgent...
> VERBOSE: Installing Azure Connected Machine Agent
> VERBOSE: Total Physical Memory:     16,067 MB
> VERBOSE: .NET Framework version: 4.8.9032
> VERBOSE: Downloading agent package from https://aka.ms/AzureConnectedMachineAgent to
> C:\Users\Corvus\AppData\Local\Temp\AzureConnectedMachineAgent.msi
> VERBOSE: Installing agent package
> Installation of azcmagent completed successfully
> Setting up auto update via Microsoft Update
> \> ConnectedMachineAgent is installed successfully
> ConnectedMachine Agent state is Disconnected. Connecting now...
> L14M-k3s is not connected to Arc
> ConnectedMachineAgent connected.
> Connecting Azure Arc-enabled Kubernetes..
> Updating kubeconfig file with Get-AksEdgeKubeConfig...
> Establishing Azure Connected Kubernetes for L14M-k3s
> ConnectedMachineAgent is connected.
> ConnectedMachineAgent is connected.
>
> **Invoke-RestMethod : Invalid URI: The hostname could not be parsed.**
> **At C:\Users\Corvus\Downloads\AKS-Edge-main\AKS-Edge-main\tools\modules\AksEdgeDeploy\AksEdge-Arc.ps1:464 char:18**
> **\+ ... response = (Invoke-RestMethod -Headers @{"Metadata" = "true"} -Method ...**
> \+                 **~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~**
> **\+    CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], UriFormatException**
> **\+    FullyQualifiedErrorId : System.UriFormatException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand**
>
> 
>
> **ERROR: (InvalidSubscriptionId) The provided subscription identifier 'resourceGroups' is malformed or invalid.**
> **Code: InvalidSubscriptionId**
> **Message: The provided subscription identifier 'resourceGroups' is malformed or invalid.**
> **Error: Arc-enabled server tag update failed**
> True

The `SubscriptionId` specified in the `aide-userconfig.json` file is correct. Further, the command still returns `True` at the end, and the connection to Arc seems to have succeeded. 

**To Reproduce**
1. Follow the [Set up machine guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine), adding a 
2. Follow the [Create full deployment guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-multi-node-deployment), adding only a Linux node. An external switch was created in Hyper-V manager as described in the guide. 
3. Follow the [Connect to Arc guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-connect-to-arc)
4. The error appears at the end of running the command `Connect-AideArc`, while waiting for `Establishing Azure Connected Kubernetes for *machine name*` to finish

**Environment (please complete the following information):**
 - AKS Edge Essentials Version AksEdge-k3s-0.7.22335.1024
 - Kubernetes version 1.23.6
 - Windows Host OS (please complete the following information):
    - Edition: Pro
    - Version: 22621.1105
    - Virtual Machine: [eg. Azure VM, Local VM, Other, None]

**Comment by parameshbabu** [comment]
is this run on an Azure VM?

**Comment by dnarh** [comment]
> is this run on an Azure VM? 

No, not running on a VM
