### ISSUE TITLE
[Question] How to expose workloads to the external network with single machine deployment?

### ISSUE THREAD

**Issue by johnliu55-msft** [Azure/AKS-Edge#54]
**Describe scenario**
I want to access the workloads deployed on AKS-Edge-Essentials from the external network with **single machine deployment**.
To clarify, the **external** network is the one where the Windows host is connected, the one colored in **brown** in the following diagram, not the internet kind of external:
![pic](https://learn.microsoft.com/en-us/azure/aks/hybrid/media/aks-edge/networking-single.png#lightbox)

**Question**
As for now, it seems like the single machine deployment only supports **internal** Vswitch, and I can't change the networking configurations (`ServiceIPRange`, `ControlPlaneEndpointIp`, ...) at all. It's always using the same fixed configuration:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/107901166/215492327-c4a2388d-ff4f-4342-8c9e-eef779f42d90.png">

And the `LoadBalancer` service is getting an internal IP (my external network is `10.30.0.0/16`):
<img width="579" alt="image" src="https://user-images.githubusercontent.com/107901166/215493500-bb365223-4dd9-4d17-8afe-d187a2173739.png">

Is this possible for single machine deployment?

**Comment by fcabrera23** [comment]
Hi @johnliu55-msft,

Thanks for your question.  Your current understanding is correct, and when you use the default networking options (using an Internal virtual switch), services will be exposed to the internal network and not accessible by external devices.

If you check your services, your service has the `192.168.0.4`  internal address, so you can use that address as your defined service address. There are two alternatives to access that service IP from external devices:

1. Keep the Internal Switch configuration and static IP deployments/services and then use port forwarding to that static IP. For example, imagine your services has the `192.168.0.20` address, and you want to forward the port `8080`, then on the Windows host OS you should run the following command: `netsh interface portproxy add v4tov4 listenport=8080 listenaddress=0.0.0.0 connectport=8080 connectaddress=192.168.0.20`. For more information, check [Netsh interface portproxy commands](https://learn.microsoft.com/en-us/windows-server/networking/technologies/netsh/netsh-interface-portproxy).

1. Create a **ScalableCluster** deployment using an External virtual switch and keep your cluster to a single node cluster.  When doing this, your node will connect your node to your external network and services will be exposed to external devices.

Thanks,
Francisco

**Comment by johnliu55-msft** [comment]
@fcabrera23 Thanks for the confirmation. One additional question: Is it possible to deploy a scalable cluster (I suppose this means [full deployment](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-multi-node-deployment)) with only one machine?

Based on the document, it seems to me that full deployment requires at least two machines, one for the control plane and the other for the worker nodes.
<img width="821" alt="image" src="https://user-images.githubusercontent.com/107901166/215927468-46558095-e6f1-49ea-aafb-d82c870aef64.png">

**Comment by fcabrera23** [comment]
Hi @johnliu55-msft,

Sorry for the delayed response. Yes, you can deploy a scalableCluster using a single machine. 

Thanks,
Francisco
