### ISSUE TITLE
[Question] Does the order of deployment steps matter?

### ISSUE THREAD

**Issue by dnarh** [Azure/AKS-Edge#55]
When creating a full deployment with multiple nodes, I get different results based on the order in which the deployment steps are done.

1. If the full deployment is created on one node and then scaled out to the remaining nodes locally, and then connecting the cluster to Azure Arc, I get the `kube-aad-proxy` pod issue as described in #20 .
2. If the full deployment is created on one node, and connected to Azure Arc before the remaining nodes are connected to the cluster, the Azure Arc connection completes successfully. The cluster is also successfully scaled to the remaining nodes afterwards. However, I experience issues with deploying and running services on the cluster.

**Question**
When creating a full deployment with multiple nodes, does the order in which scaling out the deployment to multiple nodes and connecting to Azure Arc matter? Is the second approach considered a correct way of creating a deployment, or could the issues I'm experiencing be related to the cluster not being set up properly?

**Comment by krdhruva** [comment]
@dnarh, Arc onboarding should not be dependent on order of deployment provided there is sufficient resources available on single node.

If issue still persists, I would recommend to troubleshoot issue as per instructions here: https://learn.microsoft.com/en-us/azure/azure-arc/kubernetes/diagnose-connection-issues

**Comment by fcabrera23** [comment]
Hi,

Closing this issue do to confirmation from the Arc team and inactivity in the last month.

Thanks,
Francisco
