### ISSUE TITLE
Deployment fails waiting for node to be ready

### ISSUE THREAD

**Issue by sokunna** [Azure/AKS-Edge#56]
**Describe the bug**
Deploying k3s full deployment with an external switch. The VM got created but then stuck waiting for kubernetes node to be ready.  Then it times out and the VM got removed. 

**To Reproduce**
1. Follow instruction to install AKS Edge
2. Then run this command: New-AksEdgeDeployment -JsonConfigFilePath .\aksedge-config.json
3. Deployment fails

**Expected behavior**
Deployment should succeed or a better error message why it fails so it can be corrected.

**Screenshots**
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/30151191/216148402-a6d781ce-e78f-49c7-b64d-333435508cc7.png">

**Environment (please complete the following information):**
<img width="714" alt="image" src="https://user-images.githubusercontent.com/30151191/216148634-469b008f-dbd0-4880-b213-e96c6c7891c8.png">

**Comment by fcabrera23** [comment]
Hi @sokunna,

Thanks for reaching out. Could you please try our latest [1.0.266.0](https://github.com/Azure/AKS-Edge/releases/tag/1.0.266.0) update and confirm if you're still seeing the same issue?

Thanks,
Francisco

**Comment by sokunna** [comment]
thanks @fcabrera23. The deployment worked with build 1.0.266.0.
