### ISSUE TITLE
[Feature] Option to install CSI Proxy on Windows Node

### ISSUE THREAD

**Issue by mbelt** [Azure/AKS-Edge#57]
**Description:**
[Azure File CSI Driver](https://github.com/kubernetes-sigs/azuredisk-csi-driver/tree/master/deploy/example/windows) cannot currently be installed on AKS-Edge because the Windows node does not have [CSI-Proxy](https://github.com/kubernetes-csi/csi-proxy) installed.

**Describe the solution you'd like**
Add a new option to the deployment configuration.
```
{
  "WindowsVM": {
    "csiProxyURL": "https://acs-mirror.azureedge.net/csi-proxy/v1.0.2/binaries/csi-proxy-v1.0.2.tar.gz",
    "enableCSIProxy": true
  }
}
```

**Alternatives**
There are currently no alternatives for mounting AzureFile into a container.

**Comment by fcabrera23** [comment]
Hi @mbelt,

Thanks for reaching out. We'll consider this enhancement for future releases.   Can you install the CSI-Proxy to the Windows node? What's the error you're getting?

Thanks,
Francisco
