### ISSUE TITLE
[BUG] "Invalid URI" when connecting to Azure Arc

### ISSUE THREAD

**Issue by dnarh** [Azure/AKS-Edge#60]
**Describe the bug**
Following the [How-to](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-connect-to-arc) for AKS Edge, setting up a scalable k3s deployment with three nodes (one control plane and two worker nodes) and connecting to Azure Arc. In step 3, while waiting for the `Connect-AksEdgeArc` command to finish, the following error occurs:

> PS C:\AKS-Edge-main\tools> Connect-AksEdgeArc -JsonConfigFilePath .\aksedge-config.json 
> [02/07/2023 10:42:42] *** No errors found in the connect Azure Arc configuration. 

> [02/07/2023 10:42:42] AksEdge - Connecting cluster to Azure Arc - Checking Az PS module dependencies
> - Checking helm dependency
> - Connecting to Azure Account
> - Verifying Azure Account connection ...
> - Verifying the Azure resource providers Microsoft.Kubernetes, Microsoft.KubernetesConfiguration, Microsoft.ExtendedLocation are registered
> - Resource provider Microsoft.Kubernetes is registered.
> - Resource provider Microsoft.KubernetesConfiguration is registered.
> - Resource provider Microsoft.ExtendedLocation is registered.
> - Checking whether cluster 'L14-FULL-k3s' is connected to Azure Arc...
> - All checks succeeded. Connecting cluster to Azure Arc. 

> [02/07/2023 10:43:06] Exception Caught!!! 
> - Exception calling ".ctor" with "1" argument(s): "Invalid URI: The hostname could not be parsed." (AksEdge.psm1:2653)

**To Reproduce**

1. Follow the [Set up machine guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine).
2. Follow the [Create full deployment guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-multi-node-deployment), adding only a Linux node. An external switch was created in Hyper-V manager as described in the guide.
3. Follow the [Scale out deployment guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-scale-out) and scale the cluster out with Linux nodes on two secondary machines.
4. On the primary machine, follow the [Connect to Arc guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-connect-to-arc).
5. The error appears while waiting for the command `Connect-AksEdgeArc` to succeed.

**Environment (please complete the following information):**
 - AKS Edge Essentials Version AksEdge-K3s-1.0.266.0
 - Kubernetes version 1.24.3
 - Windows Host OS (please complete the following information):
    - Edition: Pro
    - Version: 22621.1105
    - Virtual Machine: None

**Comment by dnarh** [comment]
Seems to be related to #49 .

**Comment by parameshbabu** [comment]
@dnarh  can you check the location attribute value? we seem to see this issue when we have the location attribute in json as "East US" instead of "eastus". Can you please check and confirm this? thanks.

**Comment by dnarh** [comment]
I can confirm that replacing "West Europe" with "westeurope" in the config fixed this issue.

**Comment by fcabrera23** [comment]
Hi @danchartier,

Thanks for the confirmation. We will have a location check in the upcoming version. 

Thanks,
Francisco
