### ISSUE TITLE
[Question]: How to specify an external switch?

### ISSUE THREAD

**Issue by sokunna** [Azure/AKS-Edge#61]
I'm trying to deploy k3s full deployment but the VM keeps getting an internal IP address instead of an external one that I specify in the config file. From the logs it looks like it's using an internal switch instead of the external switch. The document is unclear on how to specify an existing external switch with a Wi-Fi adapter.

**Comment by parameshbabu** [comment]
specify the DeploymentType as "ScalableCluster" instead of "SinglemachineCluster" in your json file

**Comment by sokunna** [comment]
That works. Thank you @parameshbabu
