### ISSUE TITLE
[BUG] New-AksEdgeDeployment and Install-AksEdgeHostFeatures failed when using french locale "fr-FR"

### ISSUE THREAD

**Issue by sealbus** [Azure/AKS-Edge#63]
**Describe the bug**
Following the [How-to](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine) for AKS Edge Essentials, step to check device settings failed with the following error:

> PS C:\Users\repos\AKS-Edge\tools> INstall-AksEdgeHostFeatures -Verbose
Confirm
Are you sure you want to perform this action?
Performing the operation "Install the required features" on target "AksEdge Deployment".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
VERBOSE: Configuration 'scaleSwitchAction' is not present. A default will be applied.
VERBOSE: Configuration 'deploymentType' is not present. A default will be applied.
VERBOSE: Configuration 'networkMTU' is not present. A default will be applied.
VERBOSE: Configuration 'adapterName' is not present. A default will be applied.
VERBOSE: Configuration 'httpProxy' is not present. A default will be applied.
VERBOSE: Configuration 'workerNodeUpgradeStaged' is not present. A default will be applied.
VERBOSE: Configuration 'httpsProxy' is not present. A default will be applied.
VERBOSE: Configuration 'deploymentState' is not present. A default will be applied.
VERBOSE: Configuration 'noProxy' is not present. A default will be applied.
VERBOSE: Configuration 'internetDisabled' is not present. A default will be applied.
VERBOSE: Configuration 'skipAddressFreeCheck' is not present. A default will be applied.
VERBOSE: Configuration 'isoFilePath' is not present. A default will be applied.
VERBOSE: Perform operation 'Enumerate CimInstances' with following parameters, ''namespaceName' = root\cimv2,'className' = Win32_OperatingSystem'.
VERBOSE: Operation 'Enumerate CimInstances' complete.
> - Checking host for required features
 >- Checking the status of 'Microsoft-Hyper-V'
VERBOSE: Version de l’image cible 10.0.19044.2486
 >- Checking the status of 'Microsoft-Hyper-V-Management-PowerShell'
VERBOSE: Version de l’image cible 10.0.19044.2486
 >- Checking the status of 'Microsoft-Hyper-V-Hypervisor'
VERBOSE: Version de l’image cible 10.0.19044.2486
 >- Checking the status of 'OpenSSH.Client*'
VERBOSE: Version de l’image cible 10.0.19044.2486
 >- Checking power management settings of the Host

> [02/15/2023 10:01:02] Exception Caught!!!
> - Length cannot be less than zero. (Parameter 'length') (AksEdge-Core.psm1:821)
VERBOSE: Caught Exception: Exception: Length cannot be less than zero. (Parameter 'length')
at Get-HostHibernationSetting, C:\Program Files\WindowsPowerShell\Modules\AksEdge\1.0.266.0\AksEdge-Core.psm1: line 821
at Test-HostPowerManagementSettings, C:\Program Files\WindowsPowerShell\Modules\AksEdge\1.0.266.0\AksEdge-Core.psm1: line 1796
at Test-AksEdgeHostFeaturesInternal, C:\Program Files\WindowsPowerShell\Modules\AksEdge\1.0.266.0\AksEdge-Core.psm1: line 6115
at Install-AksEdgeHostFeatures, C:\Program Files\WindowsPowerShell\Modules\AksEdge\1.0.266.0\AksEdge-Core.psm1: line 6220
at <ScriptBlock>, <No file>: line 1
True

After looking AksEdge-Core.psm1 on line 821 we can easy see on line 820 that the code is trying to substring powercfg english results, but when locale is"fr-FR" powercfg results are in french.

Locale settings on machine:

> Get-WinSystemLocale

> LCID             Name             DisplayName
> 1036             fr-FR            français (France)

**To Reproduce**
1. Have locale "fr-FR" on the machine.
2. Follow the [Set up machine guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine).

**Expected behavior**
State somewhere that only english locale are actually supported or having deployment working for any locales.

**Environment:**
 - AKS Edge Essentials Version AksEdge-K3s-1.0.266.0
 - Kubernetes version 1.24.3
 - Windows Host OS:
    - Edition: Pro
    - Version: 19044.2486
    - Virtual Machine: None

**Comment by fcabrera23** [comment]
Hi @sealbus,

Thanks for the detailed information. We will try to reproduce this issue internally and let you know. 

Thanks,
Francisco

**Comment by ChristianBeier** [comment]
Same happens with German locale.
Reproduction:
- start with a clean system set to German or French language
- follow the [how to](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine)
- `Install-AksEdgeHostFeatures` will fail with `Length cannot be less than zero. (Parameter 'length') (AksEdge-Core.psm1:821)`

**Comment by ChristianBeier** [comment]
Same happens with German locale.
Reproduction:
- start with a clean system set to German or French language
- follow the [how to](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine)
- I'nstall-AksEdgeHostFeatures' will fail with `Length cannot be less than zero. (Parameter 'length') (AksEdge-Core.psm1:821)`

**Comment by fcabrera23** [comment]
Hi @ChristianBeier & @sealbus,

We are already working on a fix for this issue that will be included in our upcoming update.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @ChristianBeier & @sealbus,

This issue was fixed with the [1.1.220.0](https://github.com/Azure/AKS-Edge/releases/tag/1.1.220.0) release.

Thanks,
Francisco
