### ISSUE TITLE
AKS-Edge Installation fails when no internet connection is available.

### ISSUE THREAD

**Issue by novatedt** [Azure/AKS-Edge#64]
The installation of AKS-Edge fails when no internet connection is available.
There are use cases where systems need to be deployed in isolated/secured environments and only after manual patching (and security scans) they would be allowed to connect to Internet.

![AKSE_Install_Error](https://user-images.githubusercontent.com/67670382/219384038-81d66dcd-eb50-4cef-9f75-9ea6b6ae83d2.png)

**Comment by fcabrera23** [comment]
Hi @novatedt,

Thanks for reaching out. We support offline scenarios; please check [Deployment configuration JSON parameters](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-deployment-config-json). We have the **Network.InternetDisabled** parameter for offline deployments. 

Also, you need to make sure you have the correct certificates installed in your Windows host OS. Please follow these steps to check if you have the required certs:

1. Run CertMgr on the Windows host OS
1. Expand Trusted Publisher \ Certificates folder
1. Open Certificate Issued To Microsoft Corporation
1. Open Certificate Path and verify that the certificate chain is complete showing the following

![image](https://user-images.githubusercontent.com/21229385/219488808-f0f1a57f-4ddf-4e3c-ba84-e5a4f9fc4b0c.png)

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @novatedt,

Closing this issue due to a lack of response for more than one month,

Thanks,
Francisco
