### ISSUE TITLE
[BUG] Cluster stuck in status "Connecting"

### ISSUE THREAD

**Issue by dnarh** [Azure/AKS-Edge#66]
**Describe the bug**
Following the [How-to](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-connect-to-arc) for AKS Edge, setting up a scalable k3s deployment with three nodes (one control plane and two worker nodes) and connecting to Azure Arc. After the connection command `Connect-AksEdgeArc` finishes with "OK", the cluster is still in status `Connecting` in the Azure portal.

**To Reproduce**

1. Follow the [Set up machine guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-setup-machine).
2. Follow the [Create full deployment guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-multi-node-deployment), adding only a Linux node. An external switch was created in Hyper-V manager as described in the guide.
3. Follow the [Scale out deployment guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-scale-out) and scale the cluster out with Linux nodes on two secondary machines.
4. On the primary machine, follow the [Connect to Arc guide](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-connect-to-arc).
5. After the command `Connect-AksEdgeArc` is finished, the cluster does not reach status `Connected` in Azure.

**Environment (please complete the following information):**
 - AKS Edge Essentials Version AksEdge-K3s-1.0.266.0
 - Kubernetes version 1.24.3
 - Windows Host OS (please complete the following information):
    - Edition: Pro
    - Version: 22621.1105
    - Virtual Machine: None

**Comment by fcabrera23** [comment]
Hi @dnarh,

Thanks for reaching out. Could you please check the Arc pods and share the logs? Probably pods are deployed but fail to connect.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @dnarh,

Thanks for the logs.  The Arc PowerShell team has updated some of the Arc modules. Also, we've updated our Arc connection PS cmdlet in our GA bits. Could you please try with the latest bits?

Thanks,
Francisco

**Comment by dnarh** [comment]
@fcabrera23  In the GA version (1.0.406.0), with a similar deployment, the cluster is stuck in status "Connecting" in Arc. Rebooting the system does not help.

As seen from the screenshot below, the `clusterconnect-agent` and `kube-aad-proxy` pods are stuck in status `CrashLoopBackOff `and `ContainerCreating`, respectively.

![pods-230222](https://user-images.githubusercontent.com/45660248/220627641-873a383f-8f3a-4369-9851-8feac9a1100a.PNG)

[clusterconnect-agent-7c9dfb446c-4xwrm.log](https://github.com/Azure/AKS-Edge/files/10804034/clusterconnect-agent-7c9dfb446c-4xwrm.log)

**Comment by fcabrera23** [comment]
Hi @dnarh,

Thanks for your update - I guess that your credentials are incorrect, and pods are failing to authenticate. I recommend following [Quickstart - Arc connection](https://github.com/Azure/AKS-Edge/tree/main/tools/modules/AksEdgeDeploy#aks-edge-essentials-arc-connection) and get all the necessary parameters and then try again.

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Hi @dnarh,

I suspect that you had the wrong file reference. Were you able to solve this issue? Can I go ahead an close it>

**Comment by fcabrera23** [comment]
Closing this bug due to inactivity.  If the issue persists, feel free to open a new bug or reopen this one.
