### ISSUE TITLE
Roadmap for AKS Edge Essentials

### ISSUE THREAD

**Issue by DavidFlamme** [Azure/AKS-Edge#69]
Hello,

We would like to use AKS Edge for small productive deployments of our application, which should be supported for many years.

Can you tell use, what the long term perspective is for AKS Edge?
When do you think it won't be in Preview state anymore?
Does Microsoft plan to officially support AKS Edge?

Best regards
   David

**Comment by chrisdats** [comment]
Hi David, As of February 21, 2023, AKS Edge Essentials is generally available. Note that some specific features are still in "preview" or "experimental." Please visit http://aka.ms/AksEdge for more information.
