### ISSUE TITLE
[BUG]: failed to create pvc

### ISSUE THREAD

**Issue by sokunna** [Azure/AKS-Edge#72]
An error installing a service that needs a persistent volume (for example, kafka).

kubectl describe pvc datadir-0-kafka-cp-kafka-0
Name:          datadir-0-kafka-cp-kafka-0
Namespace:     default
StorageClass:  local-path
Status:        Pending
Volume:
Labels:        app=cp-kafka
               release=kafka
Annotations:   volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
               volume.kubernetes.io/selected-node: aks-ledge
               volume.kubernetes.io/storage-provisioner: rancher.io/local-path
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Used By:       kafka-cp-kafka-0
Events:
  Type     Reason                Age                  From                                                                                                Message
  ----     ------                ----                 ----                                                                                                -------
  Normal   WaitForFirstConsumer  16m                  persistentvolume-controller                                                                         waiting for first consumer to be created before binding
  Normal   Provisioning          3m33s (x5 over 16m)  rancher.io/local-path_local-path-provisioner-5c64749b78-6rgk6_e4266c3e-96e3-43d4-b19a-df339bc138be  External provisioner is provisioning volume for claim "default/datadir-0-kafka-cp-kafka-0"
  Warning  ProvisioningFailed    93s (x5 over 14m)    rancher.io/local-path_local-path-provisioner-5c64749b78-6rgk6_e4266c3e-96e3-43d4-b19a-df339bc138be  failed to provision volume with StorageClass "local-path": failed to create volume pvc-6a2dba06-afff-4526-830e-6d450377906b: create process timeout after 120 seconds
  Normal   ExternalProvisioning  90s (x62 over 16m)   persistentvolume-controller                                                                         waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator

---
local-path storage class does exist.
kubectl get storageclass
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  42m

**Environment (please complete the following information):**
<img width="405" alt="image" src="https://user-images.githubusercontent.com/30151191/220685539-d1dea7b8-1e19-49a5-b814-34620ec741dd.png">

**Comment by fcabrera23** [comment]
Hi @sokunna,

Thanks for reaching out.  Although the local-path storage class is present by default, there are some components missing that will impact the creation of a PV. Could you please follow [Local Path Provisioner on Azure Kubernetes Service Edge](https://learn.microsoft.com/en-us/azure/aks/hybrid/aks-edge-howto-use-storage-local-path) and redeploy the local-path storage class and try again?

Thanks,
Francisco

**Comment by sokunna** [comment]
@fcabrera23  Yes this seems to be fixed by deleting the old storage class and creating a new one per instruction. Is there plan to have the default one worked out of the box? Thanks.

**Comment by fcabrera23** [comment]
Hi @sokunna,

Local path storage requires some containers (local-path, busybox) that Microsoft does not maintain. Hence, we do not plan to include these as part of our VHDX soon.  

Thanks,
Francisco
