### ISSUE TITLE
[Question] Are Secret objects encrypted by default?

### ISSUE THREAD

**Issue by johnliu55-msft** [Azure/AKS-Edge#77]
**Describe scenario**

**Question**
As title. And if Secret objects are not encrypted by default, is there any way to enable encryption?

**Comment by fcabrera23** [comment]
Hi @johnliu55-msft,

Thanks for reaching out. Currently, secret objects are not encrypted, this is by default in Kubernetes.  You can try [Encrypting Secret Data at Rest](https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/), although we haven't tested it and we won't be able to provide support.

Thanks,
Francisco
