### ISSUE TITLE
[Question] Trusting Corporate Proxy Certificate

### ISSUE THREAD

**Issue by biiiipy** [Azure/AKS-Edge#88]
**Describe scenario**
We are trying to install GitLab helm chart behind a corporate proxy. We have configured environment variables and the connection goes through proxy, but we are having trouble configuring to trust the proxy certificate.

```
#From https://docs.gitlab.com/charts/quickstart/
helm repo add gitlab https://charts.gitlab.io/
helm install gitlab gitlab/gitlab --set global.hosts.domain=DOMAIN --set certmanager-issuer.email=me@example.com
```
This fails with pods stuck in ImagePullBackOff state, with error **x509: certificate signed by unknown authority**:
```
FATA[0002] pulling image: rpc error: code = Unknown desc = failed to pull and unpack image 
"registry.gitlab.com/gitlab-org/build/cng/kubectl:v15.9.1": failed to resolve reference 
"registry.gitlab.com/gitlab-org/build/cng/kubectl:v15.9.1": failed to do request: 
Head "https://registry.gitlab.com/v2/gitlab-org/build/cng/kubectl/manifests/v15.9.1": 
x509: certificate signed by unknown authority
```

By SSHing (with mars command) into Linux node, we can manually pull the image with ```ctr``` and ```-k``` flag, but that's not a solution
```
sudo ctr images pull -k "registry.gitlab.com/gitlab-org/build/cng/kubectl:v15.9.1"
```

**Question**
How can we configure to trust corporate proxy certificate (or disable checking) when pulling images?

**Comment by fcabrera23** [comment]
Hi @biiiipy,

Thanks for reaching out.  If the CBL-Mariner does not trust your certificate chain, then you may need to add your root CA to the trusted store. To do so, please use the following steps:

1. Copy the root CA certificate to the AKS EE Linux VM. For more information, check [Copy-AksEdgeNodeFile](https://learn.microsoft.com/en-us/azure/aks/hybrid/reference/aks-edge-ps/copy-aksedgenodefile).  For example:
   ```
   Copy-AksEdgeNodeFile -fromFile "C:\rootCA.pem" -toFile "/home/aksedge-user/rootCA.pem" -pushFile
   ``` 
1. Using the [Invoke-AksEdgeNodeCommand](https://learn.microsoft.com/en-us/azure/aks/hybrid/reference/aks-edge-ps/invoke-aksedgenodecommand) follow the steps from [SSL CA certificates management](https://github.com/microsoft/CBL-Mariner/blob/2.0/toolkit/docs/security/ca-certificates.md) to move the certificate to the appropriate location and then `update-ca-trust`. For example:
   ```
   Invoke-AksEdgeNodeCommand "sudo mv /home/aksedge-user/rootCA.pem /etc/pki/ca-trust/source/anchors/"
   Invoke-AksEdgeNodeCommand "sudo update-ca-trust"
   ``` 

Thanks,
Francisco
