### ISSUE TITLE
[BUG] Issue with OpenSSH Client support

### ISSUE THREAD

**Issue by msandbu** [Azure/AKS-Edge#94]
When running Install-AksEdgeHostFeatures the installations stops at checking OpenSSH version of the host. 

 Install-AksEdgeHostFeatures

Confirm
Are you sure you want to perform this action?
Performing the operation "Install the required features" on target "AksEdge Deployment".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y
 - Checking host for required features
 - Checking the status of 'Microsoft-Hyper-V'
 - Checking the status of 'Microsoft-Hyper-V-Management-PowerShell'
 - Checking the status of 'Microsoft-Hyper-V-Hypervisor'
 - Checking the status of 'OpenSSH.Client*'
 - Checking power management settings of the Host
 - Checking HNS version of the Host
 - Checking OpenSSH version of the Host
 - OpenSSH.Client version does not meet the version compatible. Please manually upgrade to the latest version
True

However I'm not sure if there is a new version of OpenSSH available. This is running Windows 11 22H2 Pro. 

AKS Edge Essentials - K3s 1.0.406.0 is installed.
AksEdge version        	: 1.0.406.0
AksEdgeShell  version  	: 1.0.230221.1000
AksEdgeDeploy version  	: 1.0.230313.1200
Version	: 10.0.25314.1

Get-WindowsCapability -Online | Where-Object Name -like 'OpenSSH*'
Name  : OpenSSH.Client~~~~0.0.1.0
State : Installed

**To Reproduce**
1. Run command Install-AksEdgeHostFeatures
2. See error

**Expected behavior**
I expect the installation to continue

**Screenshots**

**Environment (please complete the following information):**
 - AKS Edge Essentials Version [e.g. 3.22]
 - Kubernetes version [e.g. 1.24.3]
 - Windows Host OS (please complete the following information):
    - Edition: [e.g. Professional, IoT Enterprise, Server, etc]
    - Version: [e.g. build 17763]
    - Virtual Machine: Local VM (Physiscal machine) 

**Additional context**

**Comment by fcabrera23** [comment]
Hi @msandbu,

Please check your OpenSSH version using the command `ssh -V` instead and share it. You probably have a version that is not supported in our current PS implementation, or maybe it's one with some well-known bugs. 

Thanks,
Francisco

**Comment by fcabrera23** [comment]
Closing this bug due to inactivity. SSH version must be checked using the `ssh -V` command.  SSH version must be great than 8.9.0.0
