### ISSUE TITLE
[Question] Are there any C# clients available to deploy workloads to Arc-enabled kubernetes?

### ISSUE THREAD

**Issue by mikanygTC** [Azure/AKS-Edge#95]
**Describe scenario**
Deploy workloads to Azure Arc Enabled AKS Edge (Device) from .NET

**Question**
The current documentation only describes use-cases where GitOps or native kubernetes CLI tools can deploy workloads to an Arc-enabled kubernetes. I am looking for a .NET client library that can target an Arc-enabled edge essentials device. In case one does not exist, what are my options? I have a central system that can create the yaml deployment manifest, and I need a way to call an API that targets the AKS Edge device through Azure ARC.

**Comment by fcabrera23** [comment]
Hi @mikanygTC,

Thanks for reaching out.  Check [Microsoft Azure Hybrid Kubernetes management client library for .NET](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resourcemanager.kubernetes-readme?view=azure-dotnet-preview). 

Thanks,
Francisco
